/**
 * P21.7 — AI Factory social post publish helper
 *
 * Encapsulates the "content_post → Publer schedule → flywheel_action" pipeline
 * for text-only (no visual asset) posts generated by the AI Factory.
 *
 * Callers:
 *   - POST /api/clients/[id]/content-posts/[postId]/publish   (manual FDE trigger)
 *   - POST /api/webhooks/publer-published                      (on confirmed publish)
 */

import { supabaseAdmin } from '@/lib/supabase'
import { getAccounts, schedulePost, type PublerAccount } from '@/lib/publer/client'
import { SOCIAL_ACTION_TYPE } from '@/lib/flywheel/vocabulary'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface ScheduleSocialPostInput {
  postId:       string
  clientId:     string
  /** ISO 8601 — defaults to 1 hour from now */
  scheduledAt?: string
  /**
   * When provided, skip this function's own (looser) account resolution
   * entirely and publish to this exact account. Callers that already ran a
   * strict resolution — e.g. resolveBoundPublerAccount() — MUST pass its
   * result through here; otherwise this function re-resolves independently
   * and can pick a different account (its fallback logic falls back to "any
   * connected account" on a stale/ambiguous binding), silently publishing an
   * unattended post to the wrong Publer account.
   */
  account?:     PublerAccount
}

export interface ScheduleSocialPostResult {
  ok:           true
  publerJobId:  string
  scheduledAt:  string
  accountId:    string
  provider:     string
}

export interface ScheduleSocialPostError {
  ok:    false
  error: string
}

// ── Strict account resolution (no fallback) ─────────────────────────────────────

/**
 * Resolves the Publer account bound to a client for a given platform —
 * strictly. Returns null if there's no binding or the bound ID doesn't match
 * a currently-connected account of that exact provider.
 *
 * This deliberately does NOT fall back to "any connected account" the way
 * scheduleSocialPost's internal resolution does for AI Factory posts (that
 * fallback exists because AI Factory content always targets a platform the
 * client is known to be active on). Callers that need a hard guarantee they're
 * posting to the right account — e.g. anything posting to a non-client-owned
 * account sharing this Publer workspace — should use this instead of calling
 * schedulePost() directly.
 *
 * Throws on a genuine `client_connectors` query failure so callers don't
 * mistake "the DB lookup errored" for "nothing is configured yet" — those
 * need different PM-facing messaging (retry vs. go set up the connector).
 * Returns null only when the lookup succeeded and there's really no binding.
 */
export async function resolveBoundPublerAccount(
  clientId: string,
  platform: string,
): Promise<PublerAccount | null> {
  const { data: connectorRow, error: connectorErr } = await supabaseAdmin
    .from('client_connectors')
    .select('config')
    .eq('client_id', clientId)
    .eq('anchor', 'publer')
    .maybeSingle()

  if (connectorErr) {
    throw new Error(`client_connectors lookup failed: ${connectorErr.message}`)
  }

  const configuredIds = (connectorRow?.config as { publer_account_ids?: Record<string, string> } | null)
    ?.publer_account_ids ?? {}
  // Case-insensitive key lookup — the connectors settings UI writes this key
  // straight from Publer's own `provider` field with no normalisation, so a
  // platform's casing here isn't guaranteed to match callers' lowercase constants.
  const platformLower = platform.toLowerCase()
  const matchedKey = Object.keys(configuredIds).find((k) => k.toLowerCase() === platformLower)
  const accountId = matchedKey ? configuredIds[matchedKey] : undefined
  if (!accountId) return null

  const accounts = await getAccounts()
  return accounts.find((a) => a.id === accountId && a.provider?.toLowerCase() === platformLower) ?? null
}

// ── Main publish function ─────────────────────────────────────────────────────

/**
 * Schedules a text-only content_post to Publer, then writes a
 * social.schedule_post flywheel_action (non-blocking on flywheel write).
 *
 * The post must have status 'approved' and belong to the given client.
 * Returns an error result instead of throwing so callers can surface it cleanly.
 */
export async function scheduleSocialPost(
  input: ScheduleSocialPostInput,
): Promise<ScheduleSocialPostResult | ScheduleSocialPostError> {
  const { postId, clientId } = input

  // 1. Load the post (ownership + status guard)
  const { data: post, error: postErr } = await supabaseAdmin
    .from('content_posts')
    .select('id, client_id, caption, script, hashtags, platforms, status')
    .eq('id', postId)
    .eq('client_id', clientId)
    .single()

  if (postErr || !post) {
    return { ok: false, error: 'content_post not found or access denied' }
  }
  if (post.status !== 'approved') {
    return { ok: false, error: `Post status is "${post.status}" — must be "approved" to publish` }
  }

  // 2. Resolve Publer account — reuse an already-verified account when the
  //    caller passed one (see ScheduleSocialPostInput.account); otherwise
  //    fall back to this function's own (looser) resolution via connector
  //    config.
  let account: PublerAccount | undefined = input.account

  if (!account) {
    const { data: connectorRow } = await supabaseAdmin
      .from('client_connectors')
      .select('config')
      .eq('client_id', clientId)
      .eq('anchor', 'publer')
      .maybeSingle()

    const rawConfig = connectorRow?.config
    const rawIds =
      rawConfig && typeof rawConfig === 'object' && !Array.isArray(rawConfig)
        ? (rawConfig as Record<string, unknown>).publer_account_ids
        : undefined
    const configuredIds: Record<string, string> =
      rawIds && typeof rawIds === 'object' && !Array.isArray(rawIds)
        ? (rawIds as Record<string, string>)
        : {}

    const postPlatforms: string[] = Array.isArray(post.platforms)
      ? (post.platforms as string[]).map(p => p.toLowerCase())
      : []

    const accounts = await getAccounts()
    account = accounts[0]

    const configuredPlatform = postPlatforms.find(p => configuredIds[p])
    if (configuredPlatform) {
      const bound = accounts.find(a => a.id === configuredIds[configuredPlatform])
      if (!bound) {
        return {
          ok: false,
          error: `Publer account binding for "${configuredPlatform}" is stale. Please reconfigure the Publishing Hub connector.`,
        }
      }
      account = bound
    } else if (postPlatforms.length > 0) {
      account = accounts.find(a => postPlatforms.includes(a.provider?.toLowerCase() ?? '')) ?? accounts[0]
    }
  }

  if (!account) {
    return { ok: false, error: 'No Publer account found for this client' }
  }

  // 3. Build caption (text-only — AI Factory posts have no visual asset)
  const hashtags = post.hashtags ? `\n\n${post.hashtags}` : ''
  const caption  = `${post.caption || post.script || ''}${hashtags}`.trim()

  if (!caption) {
    return { ok: false, error: 'Post has no caption or script content' }
  }

  const scheduledAt = input.scheduledAt ?? new Date(Date.now() + 3_600_000).toISOString()

  // 4. Schedule via Publer (text-only: media=null → networkType='status')
  let publerResult: { job_id: string }
  try {
    publerResult = await schedulePost({
      accountId:   account.id,
      provider:    account.provider,
      assetType:   'text',   // triggers networkType='status' branch
      media:       null,
      caption,
      scheduledAt,
    })
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    return { ok: false, error: `Publer scheduling failed: ${msg}` }
  }

  // 5. Update content_post to 'scheduled' + store publer_post_id
  await supabaseAdmin
    .from('content_posts')
    .update({
      status:         'scheduled',
      publer_post_id: publerResult.job_id,
      scheduled_at:   scheduledAt,
    })
    .eq('id', postId)

  // 6. Write flywheel_action (non-blocking — failure must not fail publish)
  supabaseAdmin
    .from('flywheel_actions')
    .insert({
      client_id:      clientId,
      flywheel:       'social',
      action_type:    SOCIAL_ACTION_TYPE.SCHEDULE_POST,
      execution_mode: 'third_party',
      vendor:         'publer',
      payload: {
        post_id:       postId,
        publer_job_id: publerResult.job_id,
        platform:      account.provider,
        scheduled_at:  scheduledAt,
        source:        'ai_factory',
      },
      expected_metric: 'social.posts.published_count',
      expected_delta:  1,
    })
    .then(({ error }) => {
      if (error) console.error('[scheduleSocialPost] flywheel write failed:', error.message)
    })

  return {
    ok:          true,
    publerJobId: publerResult.job_id,
    scheduledAt,
    accountId:   account.id,
    provider:    account.provider,
  }
}

// ── Flywheel outcome on confirmed publish ─────────────────────────────────────

/**
 * Called when Publer confirms a post has been published (webhook or poll).
 * Writes a social.publish_post flywheel_action for attribution.
 *
 * Non-throwing — logs and returns null on failure.
 */
export async function logSocialPublishedAction(
  postId:    string,
  clientId:  string,
  publishedAt: string,
): Promise<string | null> {
  try {
    const { data, error } = await supabaseAdmin
      .from('flywheel_actions')
      .insert({
        client_id:       clientId,
        flywheel:        'social',
        action_type:     SOCIAL_ACTION_TYPE.PUBLISH_POST,
        execution_mode:  'third_party',
        vendor:          'publer',
        payload: {
          post_id:      postId,
          published_at: publishedAt,
          source:       'ai_factory',
        },
        expected_metric: 'social.posts.published_count',
        expected_delta:  1,
      })
      .select('id')
      .single()

    if (error) {
      console.error('[logSocialPublishedAction] DB error:', error.message)
      return null
    }
    return data.id as string
  } catch (err) {
    console.error('[logSocialPublishedAction] unexpected:', err)
    return null
  }
}
