/**
 * P34.5 — vendor-name scrub tests. The core anchor: no internal vendor name
 * survives in a serialised payload (CLAUDE.md 封装名 client-facing rule).
 */
import { describe, it, expect } from 'vitest'
import { scrubString, scrubVendorNames } from '../vendor-filter'

describe('scrubString', () => {
  it.each([
    ['gpt-4o-mini', 'Content Engine'],
    ['Generated by OpenAI', 'Generated by Content Engine'],
    ['anthropic', 'Strategy Engine'],
    ['claude-sonnet-4-6', 'Strategy Engine'],
    ['data from SEMrush', 'data from Keyword Intelligence'],
    ['DataForSEO', 'Keyword Intelligence'],
    ['scraped via Jina.ai', 'scraped via Site Analyzer'],
    ['posted to Publer', 'posted to Publishing Hub'],
    ['synced from Airtable', 'synced from Content Workspace'],
  ])('scrubs %s', (input, expected) => {
    expect(scrubString(input)).toBe(expected)
  })

  it('is case-insensitive', () => {
    expect(scrubString('SEMRUSH and SemRush')).toBe('Keyword Intelligence and Keyword Intelligence')
  })

  it('leaves unrelated text untouched', () => {
    expect(scrubString('your search ranking improved')).toBe('your search ranking improved')
  })

  it('collapses duplicate packaged names from multi-token vendor phrases (狄仁杰)', () => {
    // "OpenAI GPT-4o-mini": both tokens map to Content Engine — must not double.
    expect(scrubString('OpenAI GPT-4o-mini')).toBe('Content Engine')
    expect(scrubString('built on OpenAI GPT-4o-mini today')).toBe('built on Content Engine today')
  })
})

describe('scrubVendorNames (recursive)', () => {
  it('scrubs string values inside nested objects/arrays', () => {
    const input = {
      model: 'gpt-4o-mini',
      sources: ['semrush', 'GSC'],
      nested: { note: 'written by Anthropic Claude' },
      count: 42,
      flag: true,
      empty: null,
    }
    const out = scrubVendorNames(input)
    expect(out.model).toBe('Content Engine')
    expect(out.sources).toEqual(['Keyword Intelligence', 'GSC'])
    expect(out.nested.note).toBe('written by Strategy Engine')
    // Non-strings pass through unchanged.
    expect(out.count).toBe(42)
    expect(out.flag).toBe(true)
    expect(out.empty).toBeNull()
  })

  it('does not mutate the input', () => {
    const input = { model: 'openai' }
    scrubVendorNames(input)
    expect(input.model).toBe('openai')
  })

  it('the FULL forbidden-name set is gone from a serialised payload (anchor)', () => {
    const payload = {
      a: 'openai gpt-4o', b: ['anthropic', 'claude-3-opus'], c: { d: 'semrush + dataforseo' },
      e: 'jina.ai', f: 'wavespeed flux-dev', g: 'seedance', h: 'heygen',
      i: 'airtable', j: 'publer',
    }
    const blob = JSON.stringify(scrubVendorNames(payload)).toLowerCase()
    for (const name of ['openai', 'gpt-4', 'anthropic', 'claude-', 'semrush',
      'dataforseo', 'jina', 'wavespeed', 'seedance', 'heygen', 'airtable', 'publer']) {
      expect(blob).not.toContain(name)
    }
  })
})
