import { describe, expect, it } from 'vitest'
import { detectAntibotChallenge } from '../antibot-detector'

const REAL_PAGE = `
# Hybrid Flooring Brisbane | Oztop Building Supplies

Looking for premium SPC hybrid flooring? Our Brisbane showroom stocks the full
Big Panda Lifestyle Collection in 6.5mm, 8mm and 10.5mm thicknesses. Free
measure and quote within 1 business day.

## Why hybrid flooring?
Hybrid combines the stability of laminate with the waterproof core of SPC,
giving you ...
`.repeat(8)

describe('detectAntibotChallenge — clean pages return null', () => {
  it('long real product-category content → null', () => {
    expect(detectAntibotChallenge(REAL_PAGE, 'Hybrid Flooring Brisbane | Oztop')).toBeNull()
  })

  it('short legit page (about / contact) → null', () => {
    // ~400 chars, no challenge fingerprints
    const aboutMd = 'Oztop Building Supplies has been serving Brisbane builders and homeowners since 2015. Visit our Slacks Creek showroom Mon-Fri 8-5 or call (07) 3xxx xxxx for a free measure and quote across flooring, tiles, carpet and bathware.'
    expect(detectAntibotChallenge(aboutMd, 'About Us | Oztop')).toBeNull()
  })

  it('blog post that incidentally mentions "Sucuri" in a security tutorial → null', () => {
    // Real-world false-positive trap: a security blog post may say the word.
    // The pattern requires "Sucuri Website Firewall" / "sucuri-cloudproxy" —
    // not the bare word.
    const md = REAL_PAGE + '\nWe also reviewed third-party security tools including Sucuri this quarter.'
    expect(detectAntibotChallenge(md, 'Q2 Security Tooling Review')).toBeNull()
  })
})

describe('detectAntibotChallenge — title fingerprints (SiteGround / CF / etc)', () => {
  it.each<[string, string]>([
    ['Robot Challenge Screen',              'siteground'],
    ['robot challenge screen',              'siteground'],   // case-insensitive
    ['SiteGround Security — Required Step', 'siteground'],
    ['Just a moment...',                    'cloudflare'],
    ['Wordfence — Access Blocked',          'wordfence'],
    ['Sucuri WebSite Firewall — Access Denied', 'sucuri'],
  ])('title %p → kind %p', (title, expected) => {
    const m = detectAntibotChallenge('any body content with no fingerprint', title)
    expect(m?.kind).toBe(expected)
  })

  it('records the title-based label as evidence (for the crawl_error column)', () => {
    const m = detectAntibotChallenge('', 'Robot Challenge Screen')
    expect(m?.evidence).toMatch(/Robot Challenge Screen/)
  })
})

describe('detectAntibotChallenge — body fingerprints', () => {
  it('SiteGround sg-captcha hint in markdown', () => {
    const md = REAL_PAGE + '\n<script src="/sg-captcha/loader.js"></script>'
    const m = detectAntibotChallenge(md, 'Some Page')
    expect(m?.kind).toBe('siteground')
  })

  it('Cloudflare JS-challenge wording', () => {
    const md = 'Please enable JavaScript and cookies to continue.\n\nCloudflare Ray ID: xyz'
    const m = detectAntibotChallenge(md, '')
    expect(m?.kind).toBe('cloudflare')
  })

  it('Wordfence body marker (uses NORMALIZED whitespace)', () => {
    const md = '<!-- Generated by Wordfence at server time --> Access denied.'
    const m = detectAntibotChallenge(md, 'Some Page Title')
    expect(m?.kind).toBe('wordfence')
  })

  it('Sucuri firewall body marker', () => {
    const md = 'You have been blocked by the Sucuri Website Firewall. Reference ID 12345.'
    const m = detectAntibotChallenge(md, '')
    expect(m?.kind).toBe('sucuri')
  })

  it('only scans the first 4KB to bound CPU on legit long pages', () => {
    // Bury a SiteGround marker after 5KB of padding — detector should NOT find it.
    const md = 'a'.repeat(5000) + ' sg-captcha trigger '
    const m = detectAntibotChallenge(md, 'Long Page')
    expect(m).toBeNull()
  })
})

describe('detectAntibotChallenge — generic_challenge fallbacks (lower confidence)', () => {
  it('"Access Denied" title + SHORT body → generic_challenge (catches novel WAFs)', () => {
    const m = detectAntibotChallenge('Access denied. Try again later.', 'Access Denied')
    expect(m?.kind).toBe('generic_challenge')
    expect(m?.evidence).toMatch(/short body/)
  })

  it('"Access Denied" title + LONG body → null (legit movie/film review etc)', () => {
    const m = detectAntibotChallenge(REAL_PAGE, 'Access Denied — 2008 movie review')
    expect(m).toBeNull()
  })

  it('empty title + very short body → generic_challenge (SiteGround stub case)', () => {
    const m = detectAntibotChallenge('...', '')
    expect(m?.kind).toBe('generic_challenge')
    expect(m?.evidence).toMatch(/very short body/)
  })

  it('empty title + longer body (>120 chars) → null (legit page that lost its title)', () => {
    const md = 'This is a legitimate page that for some reason has no <title> tag, but the body is clearly real content of meaningful length, not a challenge stub.'
    expect(detectAntibotChallenge(md, '')).toBeNull()
  })
})

describe('detectAntibotChallenge — null/garbage-safe', () => {
  it.each([
    [null,      null],
    [undefined, undefined],
    [42,        {}],
  ])('non-string inputs (%p / %p) do not throw', (md, t) => {
    expect(() => detectAntibotChallenge(md as unknown as string, t as unknown as string)).not.toThrow()
  })

  it('completely empty inputs → null (matches "no page fetched at all" case)', () => {
    expect(detectAntibotChallenge('', '')).toEqual({
      kind: 'generic_challenge',
      evidence: expect.stringMatching(/very short body \(0 chars\)/),
    })
  })
})

describe('detectAntibotChallenge — mutation-test canaries', () => {
  // If you delete ANY single fingerprint family from the detector arrays, the
  // matching canary below fails — proving the test set isn't a shell.
  const canaries: Array<[string, string, string]> = [
    ['siteground (title)', 'short body', 'Robot Challenge Screen'],
    ['cloudflare (title)', 'short body', 'Just a moment...'],
    ['wordfence (body)',   '<!-- Generated by Wordfence -->', 'Some Page'],
    ['sucuri (body)',      'Sucuri Website Firewall blocked this request', 'Some Page'],
  ]
  it.each(canaries)('canary [%s] fires', (_label, body, title) => {
    expect(detectAntibotChallenge(body, title)).not.toBeNull()
  })
})
