/**
 * sitemap-root — unit tests for the XML root-element scanner that replaced the
 * `/<sitemapindex/i.test(xml)` full-text substring check (Codex review on
 * PR #963, P2). Pure functions, no fetch, no network.
 */

import { describe, it, expect } from 'vitest'
import { readXmlRootElementName, isSitemapIndexDocument } from '../sitemap-root'

describe('readXmlRootElementName', () => {
  it('reads a bare root element', () => {
    expect(readXmlRootElementName('<urlset></urlset>')).toBe('urlset')
  })

  it('skips leading whitespace and newlines', () => {
    expect(readXmlRootElementName('\n\n   \t<sitemapindex/>')).toBe('sitemapindex')
  })

  it('skips a UTF-8 BOM that survived decoding', () => {
    expect(readXmlRootElementName('﻿<sitemapindex>')).toBe('sitemapindex')
    expect(readXmlRootElementName('﻿\n<urlset>')).toBe('urlset')
  })

  it('skips the XML declaration', () => {
    expect(readXmlRootElementName('<?xml version="1.0" encoding="UTF-8"?><urlset>')).toBe('urlset')
  })

  it('skips any other processing instruction', () => {
    const xml = '<?xml version="1.0"?><?xml-stylesheet type="text/xsl" href="s.xsl"?><sitemapindex>'
    expect(readXmlRootElementName(xml)).toBe('sitemapindex')
  })

  it('skips comments before the root element, including multi-line ones', () => {
    const xml = `<?xml version="1.0"?>
<!-- generated by something
     over two lines -->
<!-- and another -->
<urlset>`
    expect(readXmlRootElementName(xml)).toBe('urlset')
  })

  it('skips a doctype', () => {
    expect(readXmlRootElementName('<!DOCTYPE urlset><urlset>')).toBe('urlset')
  })

  it('ignores attributes and a default namespace on the root element', () => {
    const xml = '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'
    expect(readXmlRootElementName(xml)).toBe('sitemapindex')
  })

  it('strips a namespace prefix and lower-cases the local name', () => {
    expect(readXmlRootElementName('<sm:SitemapIndex xmlns:sm="urn:x">')).toBe('sitemapindex')
  })

  it('returns null for an empty or whitespace-only document', () => {
    expect(readXmlRootElementName('')).toBeNull()
    expect(readXmlRootElementName('   \n ')).toBeNull()
  })

  it('returns null for character data before any element', () => {
    expect(readXmlRootElementName('not xml at all')).toBeNull()
  })

  it('returns null for an unterminated prolog or start tag', () => {
    expect(readXmlRootElementName('<?xml version="1.0"')).toBeNull()
    expect(readXmlRootElementName('<!-- never closed')).toBeNull()
    expect(readXmlRootElementName('<urlset')).toBeNull()
  })

  it('returns null for a closing tag where the root should be', () => {
    expect(readXmlRootElementName('</urlset>')).toBeNull()
  })
})

describe('isSitemapIndexDocument', () => {
  it('is true for a real sitemap index, declaration/comments/attributes and all', () => {
    const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- built 2026-08-14 -->
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>https://example.com/sitemap-posts.xml</loc></sitemap>
</sitemapindex>`
    expect(isSitemapIndexDocument(xml)).toBe(true)
  })

  /**
   * The exact bug this module exists for: a `<urlset>` whose *text* contains
   * `<sitemapindex`. A substring test called this an index and fetched every
   * page <loc> as if it were a child sitemap.
   */
  it('is false for a <urlset> that merely mentions <sitemapindex> in a comment', () => {
    const xml = `<?xml version="1.0"?>
<!-- migrated from <sitemapindex> on 2026-01-01 -->
<urlset>
  <url><loc>https://example.com/a</loc></url>
</urlset>`
    expect(isSitemapIndexDocument(xml)).toBe(false)
  })

  it('is false when <sitemapindex> appears in text content or a nested position', () => {
    const inText = '<urlset><url><loc>https://example.com/a</loc></url>&lt;sitemapindex&gt;</urlset>'
    const nested = '<urlset><note><sitemapindex/></note></urlset>'
    expect(isSitemapIndexDocument(inText)).toBe(false)
    expect(isSitemapIndexDocument(nested)).toBe(false)
  })

  it('is false for an ordinary urlset and for unparseable input', () => {
    expect(isSitemapIndexDocument('<urlset></urlset>')).toBe(false)
    expect(isSitemapIndexDocument('')).toBe(false)
    expect(isSitemapIndexDocument('garbage')).toBe(false)
  })
})
