/**
 * Data Intelligence Engine — shared types (Phase 22.B).
 *
 * Consumed by:
 *   - timeseries.ts (pure functions)
 *   - insights.ts (rule engine)
 *   - API routes: /api/clients/[id]/intelligence/*
 *   - UI components: MetricSparkline, TrendCard, InsightList
 */

import type { FlywheelName } from '../adapters/types'
import type { AnomalySeverity } from '../anomaly/types'

// ─── Time bucketing ───────────────────────────────────────────────────────────

export type TimeGranularity = 'day' | 'week' | 'month'

// ─── Trend series (output of bucketing + aggregation) ─────────────────────────

/** A single time-bucketed data point. `ts` is the ISO 8601 start of the bucket. */
export interface TrendPoint {
  ts:    string   // ISO 8601 bucket start (timezone-aware)
  value: number
}

/**
 * Ordered time series for a single metric, produced by bucketByGranularity().
 * Points are sorted ascending by ts.
 */
export interface TrendSeries {
  metricKey:    string
  flywheel:     FlywheelName
  label:        string
  unit:         MetricUnit
  direction:    MetricDirection
  granularity:  TimeGranularity
  points:       TrendPoint[]
  /** Signed % change vs reference 7 days ago. Null when not enough data. */
  deltaPct7d:   number | null
  /** Signed % change vs reference 28 days ago. Null when not enough data. */
  deltaPct28d:  number | null
  /** True when ≥ 3 consecutive day-buckets have no data */
  hasDataGap:   boolean
}

// ─── Insight cards ────────────────────────────────────────────────────────────

/**
 * Structured insight generated by the rule engine.
 * Severity mirrors AnomalyDetector so UI can render a unified badge.
 * 'positive' is a 22.B addition — not present in 22.D anomaly signals.
 */
export type InsightSeverity = AnomalySeverity | 'positive'

export interface InsightCard {
  /** Stable dedup key: `<ruleId>::<clientId>::<metricKey>::<yyyymmdd>` */
  id:           string
  severity:     InsightSeverity
  flywheel:     FlywheelName
  metricKey:    string
  headline:     string
  body:         string
  deltaPct:     number | null
  currentValue: number | null
  asOf:         string    // ISO timestamp
  /** Which rule produced this card */
  sourceRule:   string
  /** Optional deep-link (e.g. to the execution item that matches this signal) */
  ctaHref?:     string
}

// ─── Summary tile (output of /intelligence/summary) ──────────────────────────

/**
 * Single-metric summary tile for the dashboard overview.
 * Contains enough info to render a TrendCard without a separate trends fetch.
 */
export interface MetricSummaryTile {
  metricKey:     string
  flywheel:      FlywheelName
  label:         string
  unit:          MetricUnit
  direction:     MetricDirection
  /** Most recent value (today or latest available) */
  currentValue:  number | null
  /** Value exactly 7 calendar days ago, or null */
  value7dAgo:    number | null
  /** Value exactly 28 calendar days ago, or null */
  value28dAgo:   number | null
  deltaPct7d:    number | null
  deltaPct28d:   number | null
  /** Ordered ascending sparkline for 28 daily points (null-filled for gaps) */
  sparkline:     Array<number | null>
}

// ─── Metric metadata ──────────────────────────────────────────────────────────

export type MetricUnit =
  | 'count'
  | 'percent'    // 0–1 range (e.g. CTR, bounce_rate)
  | 'percent100' // 0–100 range (e.g. authority_score)
  | 'currency'   // account currency, no specific symbol
  | 'ratio'      // e.g. ROAS (revenue / spend)
  | 'seconds'    // avg_session_duration
  | 'rank'       // GSC avg_position (lower = better)

export type MetricDirection = 'higher_is_better' | 'lower_is_better'

export interface MetricMeta {
  label:     string
  unit:      MetricUnit
  direction: MetricDirection
}
