/**
 * seo 泳道 —— 大部分是 legacy 在跑的能力（发现/诊断/发布），
 * 外加一个已进内核注册表的 ME2 原生 capability。
 */

import type { ProductMapComponent } from '../types'

export const SEO_COMPONENTS: readonly ProductMapComponent[] = [
  {
    id: 'module.seo-diagnosis',
    name: 'SEO 诊断（site-audit + 巡检）',
    componentType: 'module',
    businessLane: 'seo',
    dapeStages: ['discovery', 'analysis'],
    businessOutcome: '客户网站的 SEO 问题被主动发现并说清为什么,不等客户来问',
    description:
      'legacy 在跑：站点爬取/分类/富化 + 每日 SEO 巡检。不含 canonical-inventory 子目录（那是独立的 ME2 registry 组件）。未以 growth 契约重述。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    legacyOperationalNote: 'seo-patrol-daily 每日巡检 + site-audit-weekly 每周爬站（cron 注册表在案）',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: [
      'src/lib/site-audit/crawler.ts',
      'src/lib/site-audit/classifier.ts',
      'src/lib/site-audit/job-runner.ts',
      'src/lib/seo-patrol/',
    ],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_cron', ref: 'src/app/api/cron/site-audit-weekly/route.ts', verification: 'manual_claim' },
      { kind: 'caller_cron', ref: 'src/app/api/cron/seo-patrol-daily/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'capability.seo-build-publish-package',
    name: '把博客草稿打包成能发的成品',
    componentType: 'capability',
    businessLane: 'seo',
    dapeStages: ['execution', 'verification'],
    businessOutcome: '博客草稿变成完整性可验证的发布包,发布动作有据可查',
    description:
      '内核里唯一登记过的动作。线接好了,但内核本身还没在生产被调用过 —— 接线在,电没通。',
    origin: 'me2_native',
    operationalStatus: 'not_operating',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [{ type: 'requires', target: 'platform.execution-kernel' }],
    linkedIssues: [859],
    linkedPullRequests: [{ number: 863, role: 'implements' }],
    ownedPaths: ['src/lib/capabilities/seo/'],
    contractEvidence: [
      {
        kind: 'frozen_contract',
        ref: 'docs/specs/2026-08-08-me2-execution-kernel-v1.md',
        note: 'ActionDefinition（步骤/风险/幂等/成本）随内核契约冻结',
        verification: 'manual_claim',
      },
    ],
    integrationEvidence: [
      {
        kind: 'wired_registry',
        ref: 'src/lib/capabilities/index.ts',
        note: 'capability 总装点引用 ./seo/build-publish-package,再由 createKernel 接入',
        verification: 'manual_claim',
      },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'capability.seo-blog-publish',
    name: '博客发布线（草稿 → PR → 上线回执）',
    componentType: 'capability',
    businessLane: 'seo',
    dapeStages: ['execution', 'verification'],
    businessOutcome: '写好的博客能自动开 PR 发到客户站,合并后自动确认上线并请求收录',
    description: 'legacy 在跑：blog-publisher + PR 轮询对账 + GitHub webhook 收口。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    legacyOperationalNote: 'publish-blog 路由 + blog-weekly cron + GitHub webhook 全链路在生产',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [
      { type: 'consumes', target: 'adapter.github-cms' },
      { type: 'consumes', target: 'adapter.wordpress-cms' },
      { type: 'consumes', target: 'adapter.gsc', note: '上线后请求收录' },
    ],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: ['src/lib/cms/blog-publisher.ts', 'src/lib/blog/pr-sync.ts'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_route', ref: 'src/app/api/clients/[id]/cms/publish-blog/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'adapter.github-cms',
    name: '连 GitHub 的插头',
    componentType: 'adapter',
    businessLane: 'seo',
    dapeStages: ['execution'],
    businessOutcome: '「改客户网站」翻译成 GitHub 的分支/提交/PR 操作',
    description: 'legacy 在跑。零依赖 fetch 封装:读文件、开分支、提交、开/关 PR、查合并状态。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    legacyOperationalNote: '博客/GEO 片段/页面升级三条发布线都走它',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: ['src/lib/cms/github-client.ts'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'importer', ref: 'src/lib/blog/pr-sync.ts', verification: 'manual_claim' },
      { kind: 'caller_route', ref: 'src/app/api/clients/[id]/cms/publish-geo-to-github/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'adapter.wordpress-cms',
    name: '连 WordPress 的插头',
    componentType: 'adapter',
    businessLane: 'seo',
    dapeStages: ['execution'],
    businessOutcome: '「改客户网站」翻译成 WordPress REST 调用',
    description: 'legacy 在跑：文章读写、meta 更新、Yoast 探测。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: ['src/lib/cms/wordpress-client.ts'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_route', ref: 'src/app/api/clients/[id]/cms/wordpress/update-post/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'adapter.shopify-cms',
    name: '连 Shopify 的插头',
    componentType: 'adapter',
    businessLane: 'seo',
    dapeStages: ['execution'],
    businessOutcome: '「改客户店铺页面」翻译成 Shopify GraphQL 调用',
    description: 'legacy 在跑（发布路由已接）；PR #907 在补前端连接面板。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [{ number: 907, role: 'extends' }],
    ownedPaths: ['src/lib/cms/shopify-client.ts', 'src/lib/cms/shopify-guard.ts'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_route', ref: 'src/app/api/clients/[id]/cms/publish-shopify/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'adapter.gsc',
    name: '连 Google 搜索后台的插头',
    componentType: 'adapter',
    businessLane: 'seo',
    dapeStages: ['discovery', 'execution', 'verification'],
    businessOutcome: '搜索表现数据拉得回来,新页面收录请求发得出去',
    description: 'legacy 在跑：数据同步、收录请求、URL 检查、sitemap ping。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    legacyOperationalNote: 'google-data-pullback-daily cron 每日拉数',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: ['src/lib/gsc/'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_cron', ref: 'src/app/api/cron/google-data-pullback-daily/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
  {
    id: 'adapter.dataforseo',
    name: '连关键词数据源的插头',
    componentType: 'adapter',
    businessLane: 'seo',
    dapeStages: ['discovery'],
    businessOutcome: '关键词量/难度/SERP 数据有真源,不靠估和编（客户数据红线的执行件）',
    description: 'legacy 在跑：SERP、Labs、OnPage、商家数据多端点封装。',
    origin: 'legacy',
    operationalStatus: 'operating_legacy',
    declaredMaturity: 'M3_INTEGRATED',
    dependencies: [],
    linkedIssues: [],
    linkedPullRequests: [],
    ownedPaths: ['src/lib/dataforseo/'],
    contractEvidence: [],
    integrationEvidence: [
      { kind: 'caller_route', ref: 'src/app/api/clients/[id]/seo-intelligence/rankings/route.ts', verification: 'manual_claim' },
    ],
    productionEvidence: [],
    learningEvidence: [],
    currentBlockers: [],
    poDecisionRequired: [],
    ownerRole: 'claude-code',
  },
]
