/**
 * SEO Fix Orchestrator
 *
 * Executes a metadata fix for a client by:
 *  1. Loading the CMS connection (decrypted PAT — server only).
 *  2. Reading the target file from GitHub.
 *  3. Patching the metadata field in-memory (no AST).
 *  4. Creating a feature branch.
 *  5. Committing the patched file.
 *  6. Opening a pull request.
 *  7. Recording the action in flywheel_actions.
 *
 * Returns a SeoFixResult with the PR URL and the flywheel action ID.
 *
 * Security:
 *  - The decrypted PAT is used only within this function scope and never
 *    stored in any variable that escapes to a response, log, or error message.
 *  - Error messages returned to callers are sanitised (no PAT fragments).
 */

import { randomBytes } from 'crypto'
import { getConnection } from './connection-store'
import { GithubClient, GitHubApiError } from './github-client'
import { patchMetaField }             from './meta-patcher'
import { ME_BRANCH_PREFIX, CMS_ACTION_TYPE } from './vocabulary'
import type { CmsSeoFixPayload } from './vocabulary'
import { supabaseAdmin } from '../supabase'

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SeoFixInput {
  clientId:           string
  executionItemId?:   string
  productionPackageId?: string
  fix:                CmsSeoFixPayload
}

export type SeoFixResult =
  | {
      ok:             true
      prUrl:          string
      prNumber:       number
      branchName:     string
      flywheelActionId: string
    }
  | {
      ok:    false
      reason: string
      code:   SeoFixErrorCode
    }

export type SeoFixErrorCode =
  | 'NO_CONNECTION'
  | 'DECRYPT_ERROR'
  | 'GITHUB_READ_ERROR'
  | 'PATCH_ERROR'
  | 'GITHUB_WRITE_ERROR'
  | 'GITHUB_PR_ERROR'
  | 'FLYWHEEL_ERROR'

// ─── orchestrateSeoFix ────────────────────────────────────────────────────────

export async function orchestrateSeoFix(input: SeoFixInput): Promise<SeoFixResult> {
  const { clientId, executionItemId, productionPackageId, fix } = input

  // ── Step 1: Load connection (includes decrypted PAT) ───────────────────────
  let conn: Awaited<ReturnType<typeof getConnection>>
  try {
    conn = await getConnection(clientId)
  } catch (err) {
    return {
      ok:     false,
      reason: 'Failed to load CMS connection.',
      code:   'DECRYPT_ERROR',
    }
  }

  if (!conn) {
    return {
      ok:     false,
      reason: 'No GitHub CMS connection configured for this client. Set one up in Settings → 🔗 网站连接.',
      code:   'NO_CONNECTION',
    }
  }

  const { repoOwner, repoName, branch: defaultBranch, plainToken } = conn
  const github = new GithubClient(plainToken)

  // ── Step 2: Read file from GitHub ──────────────────────────────────────────
  let decodedContent: string
  let blobSha: string
  try {
    const fileData = await github.getFileContent(
      repoOwner, repoName, fix.filePath, defaultBranch,
    )
    decodedContent = fileData.decodedContent
    blobSha        = fileData.sha
  } catch (err) {
    return {
      ok:     false,
      reason: buildGithubErrMessage('reading file', err),
      code:   'GITHUB_READ_ERROR',
    }
  }

  // ── Step 3: Patch in-memory ────────────────────────────────────────────────
  const patchResult = patchMetaField(
    decodedContent, fix.slug, fix.field, fix.oldValue, fix.newValue,
  )
  if (!patchResult.ok) {
    return { ok: false, reason: patchResult.reason, code: 'PATCH_ERROR' }
  }

  // ── Step 4: Create feature branch ─────────────────────────────────────────
  const shortId    = randomBytes(4).toString('hex')
  const branchName = `${ME_BRANCH_PREFIX}${shortId}`

  let baseSha: string
  try {
    baseSha = await github.getBranchSha(repoOwner, repoName, defaultBranch)
  } catch (err) {
    return {
      ok:     false,
      reason: buildGithubErrMessage('reading branch SHA', err),
      code:   'GITHUB_READ_ERROR',
    }
  }

  try {
    await github.createBranch(repoOwner, repoName, branchName, baseSha)
  } catch (err) {
    return {
      ok:     false,
      reason: buildGithubErrMessage('creating branch', err),
      code:   'GITHUB_WRITE_ERROR',
    }
  }

  // ── Step 5: Commit the patched file ────────────────────────────────────────
  const commitMessage =
    `fix(seo): update ${fix.field} for ${fix.slug}\n\n` +
    `Reason: ${fix.reason}\n\n` +
    `Auto-generated by Magic Engine.`

  try {
    await github.commitFile(
      repoOwner, repoName, fix.filePath, branchName,
      patchResult.content, commitMessage, blobSha,
    )
  } catch (err) {
    return {
      ok:     false,
      reason: buildGithubErrMessage('committing file', err),
      code:   'GITHUB_WRITE_ERROR',
    }
  }

  // ── Step 6: Open pull request ──────────────────────────────────────────────
  const prTitle = `[ME] SEO fix: ${fix.field} for ${fix.slug}`
  const prBody  = buildPrBody(fix)

  let prUrl: string
  let prNumber: number
  try {
    const pr = await github.createPullRequest(repoOwner, repoName, {
      title: prTitle,
      body:  prBody,
      head:  branchName,
      base:  defaultBranch,
    })
    prUrl    = pr.html_url
    prNumber = pr.number
  } catch (err) {
    return {
      ok:     false,
      reason: buildGithubErrMessage('opening pull request', err),
      code:   'GITHUB_PR_ERROR',
    }
  }

  // ── Step 7: Record in flywheel_actions ────────────────────────────────────
  let flywheelActionId: string
  try {
    const { data, error } = await supabaseAdmin
      .from('flywheel_actions')
      .insert({
        client_id:              clientId,
        execution_item_id:      executionItemId      ?? null,
        production_package_id:  productionPackageId  ?? null,
        flywheel:               'seo',
        action_type:            CMS_ACTION_TYPE.META_UPDATE,
        execution_mode:         'me_auto',
        vendor:                 'github',
        payload: {
          filePath:   fix.filePath,
          slug:       fix.slug,
          field:      fix.field,
          pr_url:     prUrl,
          pr_number:  prNumber,
          branch:     branchName,
          reason:     fix.reason,
        },
        expected_metric: null,
        expected_delta:  null,
      })
      .select('id')
      .single()

    if (error) throw error
    flywheelActionId = (data as { id: string }).id
  } catch (err) {
    console.error('[seo-fix-orchestrator] flywheel insert error', err)
    // Non-fatal — PR is already open; don't fail the whole operation
    flywheelActionId = 'unknown'
  }

  return { ok: true, prUrl, prNumber, branchName, flywheelActionId }
}

// ─── Private helpers ──────────────────────────────────────────────────────────

function buildGithubErrMessage(action: string, err: unknown): string {
  if (err instanceof GitHubApiError) {
    return `GitHub error while ${action}: HTTP ${err.status}. Check repo access permissions.`
  }
  return `Unexpected error while ${action}. Please try again.`
}

function buildPrBody(fix: CmsSeoFixPayload): string {
  return [
    '## 🤖 Magic Engine — SEO Fix',
    '',
    `**File:** \`${fix.filePath}\``,
    `**Object slug:** \`${fix.slug}\``,
    `**Field updated:** \`${fix.field}\``,
    '',
    '### Change',
    '```diff',
    `- ${fix.field}: '${fix.oldValue}'`,
    `+ ${fix.field}: '${fix.newValue}'`,
    '```',
    '',
    `**Reason:** ${fix.reason}`,
    '',
    '---',
    '_Auto-generated by [Magic Engine](https://magiclab.nz). Review, then merge to deploy._',
  ].join('\n')
}
