import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

// Mock SSRF guard so tests don't do real DNS lookups (oztop.com.au etc.).
vi.mock('./ssrf-guard', () => ({
  assertPublicHost: vi.fn().mockResolvedValue(undefined),
}))

import {
  detectWafFingerprint,
  WordpressFetchError,
  type WafKind,
} from './wordpress-client'

// ─── Test helpers ─────────────────────────────────────────────────────────────

// Duck-typed Response — sidesteps subclassing differences across Node versions
// (Response.url is a prototype getter on undici; shadowing it can be flaky).
// Only the fields wordpress-client actually reads are exposed.
function makeResponse(
  body:  string,
  init?: { status?: number; url?: string; headers?: Record<string, string> },
): Response {
  const status  = init?.status ?? 200
  const url     = init?.url ?? ''
  const headers = init?.headers ?? {}
  // Normalize header keys to lower-case for .get() lookup.
  const lcHeaders: Record<string, string> = {}
  for (const [k, v] of Object.entries(headers)) lcHeaders[k.toLowerCase()] = v

  const mock = {
    ok:     status >= 200 && status < 300,
    status,
    url,
    headers: {
      get: (key: string): string | null => lcHeaders[key.toLowerCase()] ?? null,
    },
    text: async (): Promise<string> => body,
    json: async (): Promise<unknown> => JSON.parse(body),
  }
  return mock as unknown as Response
}

// ═══════════════════════════════════════════════════════════════════════════════
// detectWafFingerprint — pure-function suite
// ═══════════════════════════════════════════════════════════════════════════════

describe('detectWafFingerprint', () => {
  describe('SiteGround', () => {
    it.each<[string, string]>([
      ['https://oztop.com.au/sgcaptcha/?ref=abc',  'redirect to https://oztop.com.au/sgcaptcha/?ref=abc'],
      ['https://oztop.com.au/sg-block.html',        'redirect to https://oztop.com.au/sg-block.html'],
      ['https://oztop.com.au/sgs-block?token=1',    'redirect to https://oztop.com.au/sgs-block?token=1'],
    ])('detects SiteGround captcha via final URL (%p)', (url, expectedEvidence) => {
      const res = makeResponse('Security check', { status: 200, url })
      const fp  = detectWafFingerprint(res, 'Security check')
      expect(fp).toEqual({ kind: 'siteground', evidence: expectedEvidence })
    })

    it('detects SiteGround via body title even when URL is clean', () => {
      const res = makeResponse('<title>SiteGround Security</title>', { status: 403 })
      const fp  = detectWafFingerprint(res, '<title>SiteGround Security</title>')
      expect(fp?.kind).toBe('siteground')
    })

    it('does NOT confuse a clean URL containing "sg" in a slug', () => {
      const res = makeResponse('{}', { status: 200, url: 'https://oztop.com.au/blog/sgi-rebate-guide' })
      const fp  = detectWafFingerprint(res, '{}')
      expect(fp).toBeNull()
    })
  })

  describe('Cloudflare', () => {
    it('detects "Just a moment..." challenge page', () => {
      const body = '<html><head><title>Just a moment...</title></head></html>'
      const res  = makeResponse(body, { status: 503 })
      const fp   = detectWafFingerprint(res, body)
      expect(fp?.kind).toBe('cloudflare')
    })

    it('detects via cf-mitigated header + 403', () => {
      const res = makeResponse('forbidden', {
        status:  403,
        headers: { 'cf-mitigated': 'challenge' },
      })
      const fp = detectWafFingerprint(res, 'forbidden')
      expect(fp?.kind).toBe('cloudflare')
    })

    it('does NOT fire on cf-ray header alone with 200 OK', () => {
      const res = makeResponse('{}', {
        status:  200,
        headers: { 'cf-ray': '8a1b2c3d4e5f6789-SYD' },
      })
      const fp = detectWafFingerprint(res, '{}')
      expect(fp).toBeNull()
    })

    it('detects Cloudflare JS challenge tokens in body', () => {
      const body = '<script>window.__cf_chl_jschl="x"</script>'
      const res  = makeResponse(body, { status: 403 })
      const fp   = detectWafFingerprint(res, body)
      expect(fp?.kind).toBe('cloudflare')
    })
  })

  describe('Wordfence', () => {
    it('detects "Generated by Wordfence" body marker', () => {
      const body = '<html><!-- Generated by Wordfence at 2026-06-13 --></html>'
      const res  = makeResponse(body, { status: 403 })
      const fp   = detectWafFingerprint(res, body)
      expect(fp).toEqual({ kind: 'wordfence', evidence: 'body contains Wordfence marker' })
    })

    it('detects wfwaf-authcookie set-cookie header', () => {
      const res = makeResponse('forbidden', {
        status:  403,
        headers: { 'set-cookie': 'wfwaf-authcookie-abc=value; Path=/; HttpOnly' },
      })
      const fp = detectWafFingerprint(res, 'forbidden')
      expect(fp?.kind).toBe('wordfence')
    })
  })

  describe('Sucuri', () => {
    it('detects x-sucuri-id header', () => {
      const res = makeResponse('blocked', {
        status:  403,
        headers: { 'x-sucuri-id': '12345' },
      })
      const fp = detectWafFingerprint(res, 'blocked')
      expect(fp?.kind).toBe('sucuri')
    })

    it('detects Sucuri firewall body marker', () => {
      const body = '<title>Sucuri WebSite Firewall - Access Denied</title>'
      const res  = makeResponse(body, { status: 403 })
      const fp   = detectWafFingerprint(res, body)
      expect(fp?.kind).toBe('sucuri')
    })
  })

  describe('Generic', () => {
    it('fires on 4xx + "access denied" body', () => {
      const res = makeResponse('Access Denied — your IP is blocked', { status: 403 })
      const fp  = detectWafFingerprint(res, 'Access Denied — your IP is blocked')
      expect(fp?.kind).toBe('generic')
    })

    it('does NOT fire on 200 OK even if body mentions "forbidden"', () => {
      // A legitimate 200 JSON might quote "forbidden" in an error message.
      const body = '{"message":"This action is forbidden by your role"}'
      const res  = makeResponse(body, { status: 200 })
      const fp   = detectWafFingerprint(res, body)
      expect(fp).toBeNull()
    })
  })

  describe('priority order', () => {
    it('prefers SiteGround over generic when both could match', () => {
      const res  = makeResponse('access denied', {
        status: 403,
        url:    'https://x.com/sgcaptcha/?ref=y',
      })
      const fp = detectWafFingerprint(res, 'access denied')
      expect(fp?.kind).toBe('siteground')
    })
  })

  describe('happy path', () => {
    it('returns null for a clean 200 JSON response', () => {
      const res = makeResponse('{"id": 1}', { status: 200, url: 'https://oztop.com.au/wp-json/wp/v2/posts/1' })
      const fp  = detectWafFingerprint(res, '{"id": 1}')
      expect(fp).toBeNull()
    })

    it('only scans first 2KB to bound CPU', () => {
      // Pad the body with 100KB of junk, then a WAF marker buried at the end.
      const filler  = 'x'.repeat(100 * 1024)
      const body    = filler + 'Generated by Wordfence'
      const res     = makeResponse('', { status: 403 })
      const fp      = detectWafFingerprint(res, body)
      // Marker beyond the 2KB window → not detected (intentional bound).
      expect(fp).toBeNull()
    })
  })

  describe('mutation test self-check', () => {
    // Force-fire each detector. If you comment any single detector out, the
    // matching case here should fail — proving the test isn't a no-op shell.
    const cases: Array<{ kind: WafKind; res: Response; body: string }> = [
      { kind: 'siteground', res: makeResponse('', { status: 200, url: 'https://x.com/sgcaptcha/' }), body: '' },
      { kind: 'cloudflare', res: makeResponse('<title>Just a moment...</title>', { status: 503 }), body: '<title>Just a moment...</title>' },
      { kind: 'wordfence',  res: makeResponse('Generated by Wordfence', { status: 403 }),           body: 'Generated by Wordfence' },
      { kind: 'sucuri',     res: makeResponse('blocked', { status: 403, headers: { 'x-sucuri-id': '1' } }), body: 'blocked' },
      { kind: 'generic',    res: makeResponse('access denied', { status: 403 }),                    body: 'access denied' },
    ]
    it.each(cases)('canary: $kind detector fires when expected', ({ kind, res, body }) => {
      const fp = detectWafFingerprint(res, body)
      expect(fp?.kind).toBe(kind)
    })
  })
})

// ═══════════════════════════════════════════════════════════════════════════════
// WordpressFetchError class
// ═══════════════════════════════════════════════════════════════════════════════

describe('WordpressFetchError', () => {
  it('extends Error so existing try/catch in callers still works', () => {
    const err = new WordpressFetchError('boom', 'TIMEOUT')
    expect(err).toBeInstanceOf(Error)
    expect(err.message).toBe('boom')
    expect(err.code).toBe('TIMEOUT')
    expect(err.name).toBe('WordpressFetchError')
  })

  it('preserves httpStatus + evidence', () => {
    const err = new WordpressFetchError('block', 'WORDFENCE_BLOCK', 403, 'cookie present')
    expect(err.httpStatus).toBe(403)
    expect(err.evidence).toBe('cookie present')
  })
})

// ═══════════════════════════════════════════════════════════════════════════════
// wpFetch + expectJson behaviour through the public API surface
// (we exercise via probeYoastMetaWritable since wpFetch/expectJson are internal)
// ═══════════════════════════════════════════════════════════════════════════════

describe('expectJson WAF integration (via testWordpressConnection)', () => {
  const realFetch = globalThis.fetch
  let fetchMock: ReturnType<typeof vi.fn>

  beforeEach(() => {
    fetchMock = vi.fn()
    globalThis.fetch = fetchMock as unknown as typeof fetch
  })
  afterEach(() => {
    globalThis.fetch = realFetch
    vi.restoreAllMocks()
  })

  it('surfaces SITEGROUND_ANTIBOT in error message when captcha redirect occurs', async () => {
    fetchMock.mockResolvedValueOnce(makeResponse('<html>captcha</html>', {
      status: 200,
      url:    'https://oztop.com.au/sgcaptcha/?ref=abc',
    }))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(false)
    expect(result.error).toMatch(/SiteGround anti-bot|SITEGROUND/i)
  })

  it('surfaces WORDFENCE_BLOCK on 403 + Wordfence body', async () => {
    fetchMock.mockResolvedValueOnce(makeResponse('Generated by Wordfence', { status: 403 }))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(false)
    expect(result.error).toMatch(/Wordfence/i)
  })
})

describe('wpFetch retry behaviour (via testWordpressConnection)', () => {
  const realFetch = globalThis.fetch
  let fetchMock: ReturnType<typeof vi.fn>

  beforeEach(() => {
    fetchMock = vi.fn()
    globalThis.fetch = fetchMock as unknown as typeof fetch
  })
  afterEach(() => {
    globalThis.fetch = realFetch
    vi.restoreAllMocks()
  })

  it('retries once on 502 then succeeds', async () => {
    fetchMock
      .mockResolvedValueOnce(makeResponse('<html>Bad Gateway</html>', { status: 502 }))
      .mockResolvedValueOnce(makeResponse(
        JSON.stringify({ name: 'oztop-bot', roles: ['author'] }),
        { status: 200 },
      ))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(true)
    expect(fetchMock).toHaveBeenCalledTimes(2)
  })

  it('does NOT retry on 401 (auth error)', async () => {
    fetchMock.mockResolvedValue(makeResponse(
      JSON.stringify({ code: 'rest_unauthorized', message: 'Sorry, you are not allowed' }),
      { status: 401 },
    ))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(false)
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })

  it('does NOT retry on a captcha redirect (status 200 but WAF detected)', async () => {
    fetchMock.mockResolvedValue(makeResponse('<html>captcha</html>', {
      status: 200,
      url:    'https://oztop.com.au/sgcaptcha/?ref=abc',
    }))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(false)
    expect(fetchMock).toHaveBeenCalledTimes(1)
  })

  it('gives up after 2 tries on persistent 5xx', async () => {
    fetchMock.mockResolvedValue(makeResponse('<html>Bad Gateway</html>', { status: 502 }))
    const { testWordpressConnection } = await import('./wordpress-client')
    const result = await testWordpressConnection({
      siteUrl:     'https://oztop.com.au',
      username:    'me',
      appPassword: 'xxxx xxxx xxxx',
    })
    expect(result.ok).toBe(false)
    expect(fetchMock).toHaveBeenCalledTimes(2)
  })
})
