/**
 * POST /api/clients/[id]/cms/publish-geo-to-github
 *
 * GitHub PR-style deployment for GEO directives.
 *
 * Creates a feature branch, commits the GEO snippet as a standalone HTML file,
 * then opens a pull request against the repo's default branch.
 *
 * The FDE merges the PR in GitHub — this endpoint does NOT auto-merge.
 *
 * Body: {} (no params — uses the client's connected GitHub repo)
 *
 * Response:
 *   { success: true, pr_url: string, pr_number: number, branch: string }
 *
 * Security: requireDashboardClientAccess (session-cookie auth)
 */

import { NextRequest, NextResponse } from 'next/server'
import { requireDashboardClientAccess } from '@/lib/auth/client-access'
import { supabaseAdmin } from '@/lib/supabase'
import { getConnection } from '@/lib/cms/connection-store'
import { GithubClient, GitHubApiError } from '@/lib/cms/github-client'
import { generateDirectiveHtml } from '@/lib/geo/html-generator'
import type { GeoDirective } from '@/types/magic-engine'

interface RouteContext {
  params: { id: string }
}

export async function POST(req: NextRequest, { params }: RouteContext) {
  const { id: clientId } = params
  const access = await requireDashboardClientAccess(clientId)
  if (!access.ok) {
    return NextResponse.json({ error: access.error }, { status: access.status })
  }

  // Load GitHub connection (decrypted PAT)
  const conn = await getConnection(clientId)
  if (!conn) {
    return NextResponse.json(
      { success: false, error: 'No GitHub repository connected', code: 'NO_CONNECTION' },
      { status: 422 },
    )
  }
  if (conn.status !== 'connected') {
    return NextResponse.json(
      { success: false, error: 'GitHub connection is not verified. Re-test in Settings.', code: 'CONNECTION_NOT_VERIFIED' },
      { status: 422 },
    )
  }

  // Fetch active GEO directive
  const { data: directiveRow, error: dirErr } = await supabaseAdmin
    .from('geo_directives')
    .select('*')
    .eq('client_id', clientId)
    .eq('status', 'active')
    .maybeSingle()

  if (dirErr) {
    return NextResponse.json(
      { success: false, error: `Failed to fetch GEO directive: ${dirErr.message}` },
      { status: 500 },
    )
  }
  if (!directiveRow) {
    return NextResponse.json(
      { success: false, error: 'No active GEO directive found. Create one first.', code: 'NO_DIRECTIVE' },
      { status: 404 },
    )
  }

  const directive = directiveRow as GeoDirective
  const snippetHtml = generateDirectiveHtml(directive)

  const gh = new GithubClient(conn.plainToken)
  const owner  = conn.repoOwner
  const repo   = conn.repoName
  const base   = conn.branch || 'main'

  // Branch name: geo-directive/<directiveId short>
  const shortId    = directive.id.slice(0, 8)
  const branchName = `geo-directive/${shortId}`

  // File path in the repo
  const filePath = `geo-directives/geo-directive-${shortId}.html`

  // PR body
  const prBody = `## GEO Directive Deployment

This PR adds the GEO directive snippet for client **${clientId}** (directive \`${directive.id}\`).

### What this does
Adds a hidden GEO directive HTML file that search engine crawlers and AI agents read to understand the brand's positioning.

### Installation
After merging, include the snippet in your page \`<head>\` or as a standalone accessible URL. Then record the page URL in the Magic Engine Deploy tab.

> Generated by Magic Engine · GEO-B+ deployment`

  try {
    // 1. Get the base branch SHA
    const baseSha = await gh.getBranchSha(owner, repo, base)

    // 2. Create the feature branch
    await gh.createBranch(owner, repo, branchName, baseSha)

    // 3. Commit the GEO snippet file
    await gh.commitFile(
      owner,
      repo,
      filePath,
      branchName,
      snippetHtml,
      `feat(geo): add GEO directive snippet [Magic Engine]`,
    )

    // 4. Open a pull request
    const pr = await gh.createPullRequest(owner, repo, {
      title: `GEO Directive — ${directive.id.slice(0, 8)}`,
      body:  prBody,
      head:  branchName,
      base,
    })

    return NextResponse.json({
      success:   true,
      pr_url:    pr.html_url,
      pr_number: pr.number,
      branch:    branchName,
    })
  } catch (err) {
    if (err instanceof GitHubApiError) {
      // Branch already exists (422) means a PR was already opened
      if (err.status === 422) {
        return NextResponse.json(
          { success: false, error: `A PR branch already exists for this directive (${branchName}). Check your GitHub repo.`, code: 'BRANCH_EXISTS' },
          { status: 409 },
        )
      }
      return NextResponse.json(
        { success: false, error: `GitHub API error: ${err.message}`, code: 'GITHUB_API_ERROR' },
        { status: 502 },
      )
    }
    const message = err instanceof Error ? err.message : 'Unknown error'
    console.error('[publish-geo-to-github]', clientId, message)
    return NextResponse.json(
      { success: false, error: message, code: 'INTERNAL' },
      { status: 500 },
    )
  }
}
