-- Phase 30 S4: add geo_scope/city fields + seed Auckland RE / Brisbane Flooring / NZ 3PL

alter table baseline_domains
  add column if not exists city       text,
  add column if not exists geo_scope  text
    check (geo_scope in ('city','state','national'));

alter table baseline_domains drop constraint if exists baseline_domains_sub_industry_domain_key;
alter table baseline_domains
  add constraint baseline_domains_sub_industry_city_domain_key
  unique (sub_industry, city, domain);

update baseline_domains set geo_scope = 'national', city = null where geo_scope is null;

-- real_estate_auckland
insert into baseline_domains (industry, sub_industry, domain, keywords, geo_scope, city) values
  ('real_estate','real_estate_auckland','barfoot.co.nz',           array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','nzsothebysrealty.com',    array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','rwaucklandcentral.co.nz', array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','harcourts.net',           array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','citysales.co.nz',         array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','crockers.co.nz',          array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','auckland.bayleys.co.nz',  array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland'),
  ('real_estate','real_estate_auckland','raywhite.co.nz',          array['real estate agent auckland','auckland property for sale','auckland homes for sale','auckland real estate agency','buy house auckland','property management auckland','houses for sale auckland','auckland apartments for sale','investment property auckland','auckland real estate listings'],'city','auckland')
on conflict (sub_industry,city,domain) do nothing;

-- flooring_tiles_brisbane
insert into baseline_domains (industry, sub_industry, domain, keywords, geo_scope, city) values
  ('flooring_tiles','flooring_tiles_brisbane','theflooringguys.com.au',           array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','buildersdiscountwarehouse.com.au', array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','choicesflooring.com.au',           array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','beaumont-tiles.com.au',            array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','jimsflooring.com.au',              array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','homelyflooring.com.au',            array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','nationaltiles.com.au',             array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','thetilecollective.com.au',         array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','gotilesqld.com.au',                array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','groovetiles.com.au',               array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','carpetcourt.com.au',               array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane'),
  ('flooring_tiles','flooring_tiles_brisbane','carpetcall.com.au',                array['flooring brisbane','tiles brisbane','timber flooring brisbane','tile shop brisbane','flooring store brisbane','vinyl flooring brisbane','floor tiles brisbane','carpet brisbane','flooring installation brisbane','tile supplier brisbane'],'city','brisbane')
on conflict (sub_industry,city,domain) do nothing;

-- logistics_3pl_nz
insert into baseline_domains (industry, sub_industry, domain, keywords, geo_scope, city) values
  ('logistics_3pl','logistics_3pl_nz','onlinedistribution.co.nz', array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','stocka.co.nz',             array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','ltllogistics.co.nz',       array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','pacificomm3pl.co.nz',      array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','warehouselogistics.co.nz', array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','npfulfilment.com',          array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','epack.nz',                  array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','nzdgroup.co.nz',            array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null),
  ('logistics_3pl','logistics_3pl_nz','flowlogistics.co.nz',       array['nz fulfillment center','new zealand 3pl ecommerce','ecommerce fulfillment new zealand','nz warehousing fulfillment','third party logistics new zealand','new zealand order fulfillment','nz 3pl provider','ecommerce warehouse nz'],'national',null)
on conflict (sub_industry,city,domain) do nothing;
