/**
 * Anti-bot challenge detector for ME's crawler output.
 *
 * ## Why
 *
 * ME's site auditor pipes pages through Jina Reader, which extracts markdown
 * from the rendered HTML. But Jina sometimes still relays SiteGround /
 * Cloudflare / Wordfence / Sucuri challenge pages verbatim — those land in
 * `client_site_pages` with titles like "Robot Challenge Screen" and
 * word_count ≈ 60, polluting the entire downstream diagnostic pipeline.
 *
 * Real incident (2026-06-20 audit): 30+ Oztop product-category pages stored
 * as challenge stubs. ME-driven SEO optimisation can't run on that data —
 * the whole site looks like a stub farm.
 *
 * Fix: run this detector on every Jina result. Pages flagged as challenge
 * pages are recorded with `crawl_status='antibot_challenged'` so downstream
 * code skips them (instead of overwriting real data with stubs).
 *
 * ## Design
 *
 * - Pure function. Input = `(markdown, title)`. Output = `{ kind, evidence }`
 *   or `null`.
 * - Matches by title-substring first (cheapest), then markdown body fingerprints.
 * - Conservative: only flags HIGH-confidence signals. False-positive cost is
 *   a thin page; false-negative cost is dirty data lasting weeks.
 *
 * Companion to wordpress-client.ts `detectWafFingerprint` (P12.R.B6) — that
 * one inspects raw HTTP Response objects (status codes, headers, body up to
 * 2KB). This one works on Jina's markdown extract, where headers/status are
 * already lost and the body has been transformed.
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export type AntibotKind =
  | 'siteground'
  | 'cloudflare'
  | 'wordfence'
  | 'sucuri'
  | 'generic_challenge'

export interface AntibotMatch {
  kind:     AntibotKind
  /** One-line human-readable evidence string — goes into crawl_error column. */
  evidence: string
}

// ─── Detection rules ──────────────────────────────────────────────────────────

/**
 * Title-substring fingerprints. Case-insensitive. The exact strings here came
 * from real-world challenge pages we've seen leak into `client_site_pages`.
 *
 * Order matters only for evidence-message clarity — the first match wins.
 */
const TITLE_FINGERPRINTS: ReadonlyArray<{ kind: AntibotKind; pattern: RegExp; label: string }> = [
  // SiteGround anti-bot — the original Oztop incident.
  { kind: 'siteground',        pattern: /robot\s+challenge\s+screen/i, label: 'title contains "Robot Challenge Screen"' },
  { kind: 'siteground',        pattern: /siteground.{0,20}security/i,  label: 'title contains "SiteGround Security"' },
  // Cloudflare interactive challenge ("Just a moment...").
  { kind: 'cloudflare',        pattern: /just\s+a\s+moment\.\.\./i,    label: 'title contains "Just a moment..."' },
  // Wordfence interstitial.
  { kind: 'wordfence',         pattern: /wordfence/i,                  label: 'title contains "Wordfence"' },
  // Sucuri block page.
  { kind: 'sucuri',            pattern: /sucuri.{0,40}firewall/i,      label: 'title contains "Sucuri WebSite Firewall"' },
  // Generic catchalls — only match when accompanied by short body (checked separately).
  { kind: 'generic_challenge', pattern: /^attention\s+required/i,      label: 'title starts with "Attention Required"' },
  { kind: 'generic_challenge', pattern: /access\s+denied/i,            label: 'title contains "Access Denied"' },
  { kind: 'generic_challenge', pattern: /security\s+check/i,           label: 'title contains "Security Check"' },
]

/**
 * Markdown-body fingerprints. We scan only the first 4KB to bound CPU on
 * legitimately long pages.
 *
 * These are the same WAF families covered by B6's detectWafFingerprint, but
 * the signals here look for what survives Jina's HTML→markdown extraction
 * (no headers, no <title>, no <meta>; just plain text + occasional script
 * fragments left in code fences).
 */
const BODY_FINGERPRINTS: ReadonlyArray<{ kind: AntibotKind; pattern: RegExp; label: string }> = [
  { kind: 'siteground',        pattern: /sg[-_]?captcha/i,                 label: 'body contains sg-captcha marker' },
  { kind: 'siteground',        pattern: /\bsgs[-_]?block\b/i,              label: 'body contains sgs-block marker' },
  { kind: 'siteground',        pattern: /siteground[^\n]{0,30}\bsecurity/i, label: 'body contains SiteGround Security marker' },
  { kind: 'cloudflare',        pattern: /cf[-_]chl[-_](?:jschl|opt)/i,     label: 'body contains Cloudflare challenge token' },
  { kind: 'cloudflare',        pattern: /enable\s+javascript\s+and\s+cookies\s+to\s+continue/i, label: 'body has Cloudflare JS-challenge wording' },
  { kind: 'wordfence',         pattern: /generated\s+by\s+wordfence/i,     label: 'body contains "Generated by Wordfence"' },
  { kind: 'sucuri',            pattern: /sucuri\s+website\s+firewall/i,    label: 'body contains "Sucuri Website Firewall"' },
  { kind: 'sucuri',            pattern: /sucuri[-_]cloudproxy/i,           label: 'body contains sucuri-cloudproxy marker' },
]

const BODY_SCAN_BYTES   = 4_096
const SHORT_BODY_CHARS  = 200
const VERY_SHORT_CHARS  = 120

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Inspect a Jina-extracted page for anti-bot challenge fingerprints.
 *
 * Returns null on a clean page; an AntibotMatch when high-confidence signals
 * fire. NEVER throws.
 *
 * Decision rules (in order):
 *   1. Title-substring match → flag immediately (high confidence).
 *   2. Body-fingerprint match in the first 4KB → flag.
 *   3. Suspiciously short body (<200 chars) + generic challenge title → flag
 *      as `generic_challenge` (lower confidence, but catches novel WAFs).
 *   4. Very short body (<120 chars) + empty/missing title → flag as
 *      generic_challenge (skips pages that returned ONLY a challenge stub).
 */
export function detectAntibotChallenge(
  markdown: string,
  title:    string,
): AntibotMatch | null {
  const safeMarkdown = typeof markdown === 'string' ? markdown : ''
  const safeTitle    = typeof title    === 'string' ? title    : ''
  const trimmedTitle = safeTitle.trim()
  const scan         = safeMarkdown.length > BODY_SCAN_BYTES
    ? safeMarkdown.slice(0, BODY_SCAN_BYTES)
    : safeMarkdown

  // 1. Title fingerprints (cheapest, highest confidence).
  for (const { kind, pattern, label } of TITLE_FINGERPRINTS) {
    if (pattern.test(trimmedTitle)) {
      // For the "generic_challenge" catchalls we additionally require a short
      // body — otherwise a legit blog post titled "Access Denied (Movie Review)"
      // would false-fire.
      if (kind === 'generic_challenge') {
        if (safeMarkdown.trim().length <= SHORT_BODY_CHARS) {
          return { kind, evidence: `${label} + short body (${safeMarkdown.trim().length} chars)` }
        }
        continue
      }
      return { kind, evidence: label }
    }
  }

  // 2. Body fingerprints.
  for (const { kind, pattern, label } of BODY_FINGERPRINTS) {
    if (pattern.test(scan)) {
      return { kind, evidence: label }
    }
  }

  // 3. Very short body + empty title → generic challenge stub.
  //    SiteGround's older challenge page in particular returns a 60-char body
  //    with no <title>, so the markdown extract is just "..." or similar.
  if (safeMarkdown.trim().length <= VERY_SHORT_CHARS && trimmedTitle === '') {
    return {
      kind:     'generic_challenge',
      evidence: `very short body (${safeMarkdown.trim().length} chars) + empty title`,
    }
  }

  return null
}
