// Magic Engine — Phase Dictionary Data
// Maintained by Claude · Last updated: 2026-05-28

export type PhaseStatus = 'done' | 'active' | 'planned' | 'paused'
export type FlywheelTag = 'seo' | 'geo' | 'ads' | 'social' | 'infra' | 'ux' | 'security'

export interface SubTask {
  id: string
  title: string
  done: boolean
}

export interface Phase {
  id: string            // "12.A", "7.3", "22.D"
  name: string
  status: PhaseStatus
  completedDate?: string
  description: string
  detail: string        // extended description
  dependsOn: string[]   // phase IDs this depends on
  blocks: string[]      // phase IDs this enables
  keyFiles: string[]
  keyTables: string[]
  tags: FlywheelTag[]
  subTasks?: SubTask[]
  pr?: string
  notes?: string
}

export const PHASES: Phase[] = [
  {
    id: '1-6',
    name: '社媒内容矩阵',
    status: 'done',
    completedDate: '2026 Q1',
    description: '多客户管理、Brand Brief Studio、Campaign 批量生成、Visual/Video/Avatar Studio、Content Workspace、Publishing Hub',
    detail: '完整社媒内容生产线。Route A（关键词驱动）/ Route B（参考帧学习）/ Route C（自由主题）。支持 FB / IG / TK / YT 四平台。viral_reference_library 学习机制已内置。',
    dependsOn: [],
    blocks: ['8.R', '21', '12.B'],
    keyFiles: [
      'src/app/api/clients/[id]/social-plan/route.ts',
      'src/app/api/clients/[id]/campaign/[campaignId]/batch-generate/route.ts',
      'src/lib/social/social-plan-templates.ts',
    ],
    keyTables: ['social_plan', 'campaigns', 'viral_reference_library'],
    tags: ['social', 'content'],
  },
  {
    id: '7.1',
    name: 'AI Visibility Tracker',
    status: 'done',
    completedDate: '2026-04-30',
    description: '多引擎 AI 搜索排名追踪（OpenAI / Perplexity / Google Gemini）',
    detail: '为每个客户建立 GEO 可见度基线。avg_rank 1.49（CTS Tours）。问句必须带地域标签（"best X in New Zealand"）。支持 3 引擎对比。每周 cron 自动运行。',
    dependsOn: [],
    blocks: ['7.3', '12.I'],
    keyFiles: [
      'src/app/api/clients/[id]/ai-tracker/',
      'src/lib/ai-tracker/',
      'src/app/api/cron/ai-tracker-weekly/route.ts',
    ],
    keyTables: ['ai_tracker_queries', 'ai_tracker_runs'],
    tags: ['geo'],
  },
  {
    id: '7.2',
    name: 'GEO Composer',
    status: 'done',
    completedDate: '2026-04-30',
    description: 'GEO Directive 生成、编辑器、Snippet 部署助手',
    detail: '静态 GEO 指令注入到博客（Phase 1 MVP）。动态脚本方案延缓至 Q3+ 2026。已部署 4 页 CTS Tours GEO Directive。包含 aria-hidden 隐藏指令块注入逻辑。',
    dependsOn: ['7.1'],
    blocks: ['7.3', '12.A'],
    keyFiles: [
      'src/app/api/clients/[id]/geo-composer/',
      'src/lib/geo/',
      'src/app/api/clients/[id]/publish-geo-snippet/route.ts',
    ],
    keyTables: ['geo_directives'],
    tags: ['geo'],
  },
  {
    id: '7.3',
    name: '双信号博客生成',
    status: 'done',
    completedDate: '2026-05-05',
    description: 'SEO×GEO 双信号博客，同时携带 SEO 信号和 GEO 指令块',
    detail: 'mode 字段支持 unified / geo_only / seo_only。blog_posts 表记录 mode、source_query_id、geo_directive_id、primary_keyword + keyword_volume + keyword_kd。3 篇 GEO 博客已发布至 CTS Tours。',
    dependsOn: ['7.1', '7.2'],
    blocks: ['12.A', '12.I'],
    keyFiles: [
      'src/app/api/clients/[id]/blog/',
      'src/lib/blog/',
    ],
    keyTables: ['blog_posts', 'geo_directives'],
    tags: ['seo', 'geo'],
  },
  {
    id: '7.4',
    name: '月报 + PoC 验证',
    status: 'active',
    description: 'CTS Tours 基线已建立，每周自动追踪 AI 排名变化，第 4 周生成首份月报',
    detail: 'P7.4.14（第 2/4 周复跑 AI Tracker）和 P7.4.15（首份月报生成）尚未执行。基线数据已在 Supabase。',
    dependsOn: ['7.1', '7.3'],
    blocks: [],
    keyFiles: [],
    keyTables: ['ai_tracker_runs', 'monthly_reports'],
    tags: ['geo', 'seo'],
    subTasks: [
      { id: 'P7.4.14', title: '第 2/4 周复跑 AI Tracker', done: false },
      { id: 'P7.4.15', title: '第 4 周生成首份月报', done: false },
    ],
  },
  {
    id: '8.0',
    name: 'DNZ 采集基础设施',
    status: 'done',
    completedDate: '2026-05-05',
    description: '全站内容快照：sitemap 解析 → Jina.ai 抓取 → GPT-4o-mini 分类 → GEO 块检测',
    detail: '103 个单元测试通过（crawler 64 + classifier 20 + geo-detector 19）。覆盖率 95%+。job-runner 状态机无需 Redis。支持最多 100 页/客户。',
    dependsOn: [],
    blocks: ['8.D', '8.1'],
    keyFiles: [
      'src/lib/site-audit/crawler.ts',
      'src/lib/site-audit/classifier.ts',
      'src/lib/site-audit/geo-detector.ts',
      'src/lib/site-audit/job-runner.ts',
      'src/lib/site-audit/job-executor.ts',
    ],
    keyTables: ['client_site_pages', 'site_audit_jobs'],
    tags: ['seo', 'geo', 'infra'],
  },
  {
    id: '8.1',
    name: '三维内容策略分析',
    status: 'done',
    completedDate: '2026-05-07',
    description: '现有内容 × AI 弱项 × 关键词缺口 → 三维策略面板',
    detail: 'P8.1.1–P8.1.6 全部完成。升级/新建/社媒机会评分。防内容蚕食检测。客户接入向导 3 步：基本信息 → Airtable 配置 → 关键词参数。',
    dependsOn: ['8.0'],
    blocks: ['8.D'],
    keyFiles: ['src/app/dashboard/clients/[id]/strategy/'],
    keyTables: ['content_strategy_items'],
    tags: ['seo', 'geo'],
  },
  {
    id: '8.6',
    name: 'Link Intelligence',
    status: 'done',
    completedDate: '2026-05-01',
    description: 'DataForSEO 外链分析：DR、外链数量、来源域名',
    detail: 'DataForSEO API 直连，替代 SEMrush 节省 96–99% 成本。AU 市场默认。',
    dependsOn: [],
    blocks: ['8.C.1'],
    keyFiles: ['src/app/api/clients/[id]/link-intelligence/'],
    keyTables: [],
    tags: ['seo'],
  },
  {
    id: '8.7',
    name: 'SERP Intelligence',
    status: 'done',
    completedDate: '2026-05-01',
    description: 'DataForSEO 关键词排名追踪，SERP 结果分析',
    detail: '每周快照。支持 gl=au / gl=nz + location=Auckland, NZ 参数。与 Phase 12.I 飞轮接线。',
    dependsOn: [],
    blocks: ['8.C.1', '12.I'],
    keyFiles: ['src/app/api/clients/[id]/serp-intelligence/'],
    keyTables: ['keyword_snapshots'],
    tags: ['seo'],
  },
  {
    id: '8.8',
    name: 'Local Visibility',
    status: 'done',
    completedDate: '2026-05-01',
    description: 'DataForSEO AU/NZ 14 城市本地搜索可见度',
    detail: '覆盖 Auckland / Sydney / Melbourne / Brisbane 等主要城市。本地化信号强化。',
    dependsOn: [],
    blocks: ['8.C.1'],
    keyFiles: ['src/app/api/clients/[id]/local-visibility/'],
    keyTables: [],
    tags: ['seo'],
  },
  {
    id: '8.9',
    name: 'Market Baseline',
    status: 'done',
    completedDate: '2026-05-01',
    description: 'SEMrush 行业对标，竞品关键词 / 流量 / DA 对比',
    detail: 'SEMRUSH_DB 默认 au，可在 clients 表覆盖为 nz。',
    dependsOn: [],
    blocks: ['8.C.1'],
    keyFiles: ['src/app/api/clients/[id]/market-baseline/'],
    keyTables: [],
    tags: ['seo'],
  },
  {
    id: '8.10',
    name: 'Synthesis Layer + Deep Research 报告',
    status: 'active',
    description: '张骞 Discovery Agent + 5 层合成报告（S0–S5）',
    detail: 'S0 张骞 Discovery Agent ✅（14/14 完成，2026-05-18）。S2 数据源深化、S3 Synthesis 层、S4 Report Composer、S5 引用追溯尚未完成。',
    dependsOn: ['8.0', '8.1', '8.D'],
    blocks: ['13.A'],
    keyFiles: ['src/lib/agents/zhangqian/', 'src/app/api/clients/[id]/discovery/'],
    keyTables: ['discovery_reports', 'discovery_jobs'],
    tags: ['seo', 'geo'],
    subTasks: [
      { id: 'S0', title: '张骞 Discovery Agent', done: true },
      { id: 'S2', title: '数据源深化（~2天）', done: false },
      { id: 'S3', title: 'Synthesis 层（~3天）', done: false },
      { id: 'S4', title: 'Report Composer（~2天）', done: false },
      { id: 'S5', title: '引用/证据追溯（~1天）', done: false },
    ],
  },
  {
    id: '8.11',
    name: 'Billing Monitor',
    status: 'done',
    completedDate: '2026-05-01',
    description: 'DataForSEO 成本追踪，API 调用计费监控',
    detail: '实时显示 DataForSEO 余额和每日消耗，防止超支。',
    dependsOn: [],
    blocks: [],
    keyFiles: ['src/app/api/clients/[id]/billing-monitor/'],
    keyTables: [],
    tags: ['infra'],
  },
  {
    id: '8.12',
    name: 'AU/NZ 本地化能力扩展',
    status: 'active',
    description: 'Luban tool loop 开发中，完整 AU/NZ 本地化 14 项 MVP',
    detail: '当前：S3.1 鲁班 tool loop 开发中。其余 13 项 MVP 后补充。要求所有内容 prompt 显式声明 AU/NZ 市场，使用 AU/NZ 英语拼写。',
    dependsOn: ['1-6', '7.3'],
    blocks: ['21'],
    keyFiles: ['src/lib/agents/luban/'],
    keyTables: [],
    tags: ['seo', 'geo', 'social'],
  },
  {
    id: '8.C.1',
    name: '月报整合',
    status: 'done',
    completedDate: '2026-05-01',
    description: '6 大数据源聚合，生成 10 节月度洞察报告',
    detail: '整合 GSC + GA4 + SEMrush + DataForSEO(SERP/Link/Local) 数据。自动生成 PDF 月报。',
    dependsOn: ['8.6', '8.7', '8.8', '8.9'],
    blocks: ['9'],
    keyFiles: ['src/app/api/clients/[id]/monthly-report/'],
    keyTables: ['monthly_reports'],
    tags: ['seo', 'infra'],
  },
  {
    id: '8.D',
    name: 'DNZ 诊断驱动内容策略',
    status: 'done',
    completedDate: '2026-05-08',
    description: '先诊断再生成：DNZ 采集 → 三维分析 → 策略驱动执行',
    detail: 'Stage 1 ✅ Stage 2 ✅ Stage 3 ✅ E2E 验证 ✅。防关键词蚕食检测。升级/新建/社媒机会分类。',
    dependsOn: ['8.0', '8.1'],
    blocks: ['12.A'],
    keyFiles: ['src/lib/site-audit/', 'src/app/dashboard/clients/[id]/strategy/'],
    keyTables: ['client_site_pages', 'content_strategy_items'],
    tags: ['seo', 'geo'],
  },
  {
    id: '8.P',
    name: 'Paid Social Studio',
    status: 'paused',
    description: '暂缓 — 待客户明确 Meta 广告需求触发',
    detail: '与 Phase 18（Ads Engine）存在功能重叠，等 18.A Meta Ads MVP 落地后重新评估范围。',
    dependsOn: ['1-6'],
    blocks: [],
    keyFiles: [],
    keyTables: [],
    tags: ['ads', 'social'],
    notes: '⏸ 已暂缓，不进入 backlog 排期',
  },
  {
    id: '8.Q',
    name: '内容质控提升',
    status: 'active',
    description: '外编版本管理 + Brief 编辑 + Prompt 预览 + 质检流水线',
    detail: '8.Q.1 外编版本管理 ✅ · 8.Q.2 Brief 编辑 ✅ · 8.Q.3 Prompt 预览部分 ✅ · 8.Q.4 待做',
    dependsOn: ['1-6'],
    blocks: [],
    keyFiles: ['src/app/dashboard/clients/[id]/content/'],
    keyTables: [],
    tags: ['social', 'content'],
    subTasks: [
      { id: '8.Q.1', title: '外编版本管理', done: true },
      { id: '8.Q.2', title: 'Brief 编辑', done: true },
      { id: '8.Q.3', title: 'Prompt 预览', done: true },
      { id: '8.Q.4', title: '质检流水线', done: false },
    ],
  },
  {
    id: '8.R',
    name: 'Reels Studio',
    status: 'done',
    completedDate: '2026-05-02',
    description: '提示词生成 + 参考帧生成/上传 + I2V 视频 + 对话修改',
    detail: 'Seedance 2.0 I2V（Image-to-Video）。故事板 ChatGPT Image 生成。支持 9 panel 3×3 storyboard。Avatar Studio（HeyGen）集成。',
    dependsOn: ['1-6'],
    blocks: ['21'],
    keyFiles: ['src/app/dashboard/clients/[id]/reels/', 'src/app/api/clients/[id]/reels/'],
    keyTables: ['reels_scripts', 'visual_assets'],
    tags: ['social'],
  },
  {
    id: '9.0',
    name: 'Visual Queue UX Polish',
    status: 'done',
    completedDate: '2026-05-25',
    description: 'Visual Queue 全面打磨，含测试套件和 QueueOverviewCard',
    detail: 'P9.0.10-14 测试 + P9.0.15-17 QueueOverviewCard 全部完成。',
    dependsOn: ['1-6'],
    blocks: [],
    keyFiles: ['src/app/dashboard/content/', 'src/components/visual-queue/'],
    keyTables: ['visual_queue'],
    tags: ['ux'],
  },
  {
    id: '9',
    name: '报告化 + 客户 Portal',
    status: 'planned',
    description: '月报 PDF 自动生成 + 邮件发送 + 客户 Portal 完整体验',
    detail: '依赖 Phase 8.C.1（月报数据）和 Phase 13.UI（Portal UI）。包含站点权威度追踪（DA / 外链 / 内链）。',
    dependsOn: ['8.C.1', '13.A'],
    blocks: ['10'],
    keyFiles: ['src/app/portal/'],
    keyTables: ['monthly_reports', 'client_portal_users'],
    tags: ['infra', 'ux'],
  },
  {
    id: '12.A',
    name: '飞轮数据骨架 + CTS GEO 端到端 Demo',
    status: 'done',
    completedDate: '2026-05-17',
    description: '15 个 flywheel 核心任务全部完成。3 张飞轮表 + CTS 第一条 outcome 卡片',
    detail: '奠定飞轮数据基础设施。flywheel_actions / flywheel_metrics / flywheel_outcomes 三表创建。M3 里程碑：CTS 真实数据跑出第一条 outcome 卡片（含 baseline/after/verdict）。',
    dependsOn: ['7.3', '7.2'],
    blocks: ['12.B', '12.C', '12.G', '12.I', '17.A', '18.A', '22', '22.D', '23'],
    keyFiles: [
      'supabase/migrations/flywheel*.sql',
      'src/lib/flywheel/',
    ],
    keyTables: ['flywheel_actions', 'flywheel_metrics', 'flywheel_outcomes'],
    tags: ['infra', 'seo', 'geo', 'ads', 'social'],
    pr: '#PR merge to main',
  },
  {
    id: '12.B',
    name: 'SEO / Ads / 社媒 Adapter 接入',
    status: 'done',
    completedDate: '2026-05-18',
    description: '三条飞轮 adapter：SEO 博客发布 → flywheel_actions / Ads Fix → flywheel_actions / 社媒发布 → flywheel_actions',
    detail: 'B.1–B.4 全部完成。每个 adapter 将第三方执行结果写回飞轮表。source 字段：diagnostic / marketing_plan / fde_manual / proactive_signal。',
    dependsOn: ['12.A'],
    blocks: ['12.C', '12.I', '18.A', '21'],
    keyFiles: ['src/lib/flywheel/adapters/'],
    keyTables: ['flywheel_actions'],
    tags: ['seo', 'ads', 'social', 'infra'],
  },
  {
    id: '12.C',
    name: '飞轮聚合视图 + 华佗置信度 + Publer 回流',
    status: 'done',
    completedDate: '2026-05-21',
    description: '飞轮聚合视图 + 华佗 outcome 置信度反哺 + Publer engagement 数据回流',
    detail: '华佗 agent 评估 flywheel_outcomes.confidence。Publer 帖子 likes/comments/shares 每日 cron 写入 flywheel_metrics。',
    dependsOn: ['12.B'],
    blocks: ['22'],
    keyFiles: ['src/lib/agents/huatuo/', 'src/app/api/cron/social-engagement-pullback/'],
    keyTables: ['flywheel_outcomes', 'flywheel_metrics'],
    tags: ['social', 'infra'],
  },
  {
    id: '12.G',
    name: '诸葛亮策略调度引擎',
    status: 'done',
    completedDate: '2026-05-21',
    description: 'P12.G.1–G.5 全部完成。诸葛亮调度飞轮任务优先级 + Plan 生成',
    detail: '诸葛亮作为 Strategy Engine（Claude Sonnet）。调度所有 4 条飞轮任务。生成 Plan → 执行看板任务树。zhuge_session_id 追踪。',
    dependsOn: ['12.A'],
    blocks: ['22.D', '23'],
    keyFiles: ['src/lib/agents/zhugeliang/', 'src/app/api/clients/[id]/zhugeliang/'],
    keyTables: ['flywheel_actions'],
    tags: ['infra'],
  },
  {
    id: '12.H',
    name: 'GitHub CMS 执行闭环',
    status: 'done',
    completedDate: '2026-05-25',
    description: '博客通过 GitHub API 发布到 CMS，形成完整 SEO 内容闭环',
    detail: 'P12.H.1-3 全部完成。发布后 URL 写回 flywheel_actions 归因。',
    dependsOn: ['12.A', '7.3'],
    blocks: [],
    keyFiles: ['src/lib/github-cms/', 'src/app/api/clients/[id]/blog/publish/'],
    keyTables: ['flywheel_actions', 'blog_posts'],
    tags: ['seo'],
  },
  {
    id: '12.I',
    name: 'SEO Intelligence 页面 + 飞轮闭环',
    status: 'done',
    completedDate: '2026-05-22',
    description: 'P12.I.1–I.10 完成。SEO Intelligence 页面 + 关键词快照 cron + 飞轮接线',
    detail: '关键词排名趋势图。每周 DataForSEO 快照 cron。与飞轮 outcome 归因接线。M3 验证待 PM 确认。',
    dependsOn: ['8.7', '12.A'],
    blocks: [],
    keyFiles: ['src/app/dashboard/clients/[id]/seo-intelligence/'],
    keyTables: ['keyword_snapshots', 'flywheel_actions'],
    tags: ['seo'],
  },
  {
    id: '12.J',
    name: '博客头图配图生成',
    status: 'done',
    completedDate: '2026-05-23',
    description: '博客发布前自动生成 Atlas 头图（Visual Studio）',
    detail: 'P12.J.1 ✅ P12.J.2 ✅。头图生成走 Atlas Cloud（WaveSpeed Flux-dev）。',
    dependsOn: ['7.3'],
    blocks: [],
    keyFiles: ['src/app/api/clients/[id]/blog/generate-header-image/'],
    keyTables: ['blog_posts'],
    tags: ['seo', 'content'],
  },
  {
    id: '12.K',
    name: 'Campaign 视觉方向',
    status: 'done',
    completedDate: '2026-05-23',
    description: 'Campaign 级别统一视觉风格指南生成',
    detail: 'P12.K.1 ✅。为每个 Campaign 生成 Visual Direction Brief，驱动 Visual Studio 生图一致性。',
    dependsOn: ['1-6'],
    blocks: [],
    keyFiles: ['src/app/api/clients/[id]/campaign/[campaignId]/visual-direction/'],
    keyTables: ['campaigns'],
    tags: ['social'],
  },
  {
    id: '12.Q',
    name: '内容质量闭环',
    status: 'done',
    completedDate: '2026-05-21',
    description: '内容评分 + 质检 + 修订闭环，提升批量生产质量',
    detail: '全部完成。质检结果写回 flywheel 归因。',
    dependsOn: ['12.A', '1-6'],
    blocks: [],
    keyFiles: [],
    keyTables: [],
    tags: ['content'],
  },
  {
    id: '13.A',
    name: 'Prospect 注册流程',
    status: 'done',
    completedDate: '2026-05-25',
    description: '/discover Magic Link + 诊断报告 + Portal 处方门控',
    detail: 'P13.A.7 portal magic link 修复 ✅。/portal/login 路由修复。浏览器 callback 处理 magic-link hash。client_portal_users email 首次注册 Auth user。',
    dependsOn: ['8.10'],
    blocks: ['9'],
    keyFiles: ['src/app/discover/', 'src/app/prospect/', 'src/app/portal/login/'],
    keyTables: ['client_portal_users'],
    tags: ['ux'],
  },
  {
    id: '14',
    name: 'Website Connector',
    status: 'planned',
    description: '网站直连执行闭环：WordPress 连接器（近期优先）',
    detail: 'P14.A.5 WordPress 连接器为近期优先级。直接向客户网站发布 SEO 内容，无需人工操作。',
    dependsOn: ['12.H'],
    blocks: [],
    keyFiles: [],
    keyTables: [],
    tags: ['seo', 'infra'],
  },
  {
    id: '15',
    name: 'Reputation Engine',
    status: 'planned',
    description: '口碑监控与执行闭环（战略已确认，待排期）',
    detail: 'reputation 维度：只诊断不接入飞轮（FDE 外部完成）。监控 Google Reviews / 媒体提及。',
    dependsOn: ['12.A'],
    blocks: [],
    keyFiles: [],
    keyTables: [],
    tags: ['infra'],
    notes: '📋 reputation + competitor 维度只诊断不接入飞轮',
  },
  {
    id: '16',
    name: 'Competitor Intelligence',
    status: 'planned',
    description: '竞品雷达 + 信号驱动执行（战略已确认，待排期）',
    detail: 'competitor 维度：只诊断不接入飞轮。基于 DataForSEO 竞品关键词 / SERP 分析。',
    dependsOn: ['8.7', '12.A'],
    blocks: [],
    keyFiles: [],
    keyTables: [],
    tags: ['seo'],
  },
  {
    id: '17.A',
    name: '统一数据回流层',
    status: 'done',
    completedDate: '2026-05-27',
    description: 'GSC / GA4 数据回流 + 飞轮归因桥接 + 每日 cron + 客户「数据」tab',
    detail: 'P17.A.1–A.6 全部完成，merge。GSC totals 修复（查询站点级别聚合而非 Top-50 行求和）。GA4 keyEvents 指标。每日 cron 自动同步。',
    dependsOn: ['12.A'],
    blocks: ['22', '22.D'],
    keyFiles: [
      'src/app/api/clients/[id]/gsc/',
      'src/app/api/clients/[id]/ga4/',
      'src/app/api/cron/data-pullback/',
      'src/components/client/ClientDataTab.tsx',
    ],
    keyTables: ['flywheel_metrics'],
    tags: ['seo', 'infra'],
  },
  {
    id: '17.B',
    name: 'Meta Page Insights 回流',
    status: 'planned',
    description: 'Meta Graph API Page Insights：帖子互动 + 粉丝增长 cron 回流',
    detail: '与 Meta Ads API（Phase 18）不同：Graph API for Page（非 Ads Manager）。需要 System User Token via Agency BM。Meta App 需要 Agency BM 验证后创建。',
    dependsOn: ['12.A'],
    blocks: ['22'],
    keyFiles: ['src/app/api/clients/[id]/meta-page-insights/'],
    keyTables: ['flywheel_metrics'],
    tags: ['social'],
    notes: '⚠️ Meta Developer App 创建前需先验证 Agency BM',
  },
  {
    id: '18.A',
    name: 'Meta Ads MVP',
    status: 'active',
    description: 'Meta Ads 诊断 → Fix 按钮接线 Meta MCP（P18.A.1–A.3）',
    detail: '已有 Meta Ads MCP 连接。Fix 按钮：暂停亏损关键词/调整出价/添加否定词。Talk to Us：重构结构/预算策略/创意方向。⚠️ PR #107 P1：未校验广告实体归属（越权漏洞，待修复）。',
    dependsOn: ['12.A', '12.B'],
    blocks: ['18'],
    keyFiles: [
      'src/app/api/clients/[id]/meta-ads/',
      'src/app/api/clients/[id]/meta-ads/fix/route.ts',
      'src/components/ads/MetaAdsCampaignPanel.tsx',
    ],
    keyTables: ['flywheel_actions'],
    tags: ['ads'],
    notes: '🔴 P1 安全漏洞待修复（PR #107）',
  },
  {
    id: '19',
    name: 'API 鉴权整改 / IDOR 修复',
    status: 'done',
    completedDate: '2026-05-27',
    description: '89 个 /api/clients/[id]/* 路由 IDOR 封堵 + NEXT_PUBLIC 密钥泄漏清除',
    detail: '19.A–E 全部完成，PR #95。requireDashboardClientAccess guard 全面覆盖。注意：fde access_type 尚未加入白名单（PR #95 P2 待修复）。',
    dependsOn: [],
    blocks: [],
    keyFiles: ['src/lib/auth/requireDashboardClientAccess.ts', 'src/lib/auth/guardAdmin.ts'],
    keyTables: [],
    tags: ['security'],
    pr: '#95',
  },
  {
    id: '20.D',
    name: '统一看板入口 / FDE 手动录入',
    status: 'done',
    completedDate: '2026-05-28',
    description: '六支柱看板 + FDE「＋录入工作」+ 拖拽排序 + Portal 分组',
    detail: 'fde_manual source migration + /execution/manual API + FdeManualEntryModal + 看板「＋录入工作」按钮 + FDE 分组 + 拖拽排序 + Portal 分组展示 + PlanTask.requires 素材标注。⚠️ PM 还需运行 migration + 验收。',
    dependsOn: ['12.A'],
    blocks: [],
    keyFiles: [
      'src/app/api/clients/[id]/execution/manual/route.ts',
      'src/components/execution/FdeManualEntryModal.tsx',
    ],
    keyTables: ['flywheel_actions', 'execution_items'],
    tags: ['ux'],
    notes: '⚠️ PM 待验收 + 跑 migration',
  },
  {
    id: '21',
    name: 'AI Content Factory',
    status: 'planned',
    description: '旗舰能力：FDE 客户默认产能引擎，批量生成一周社媒日历',
    detail: '三层：calendar skeleton（Supabase 表结构） + generation API（按平台批量调用 social-plan）+ Publer bulk scheduling + week-view UI + 行内标注。Phase 21.A（日历 DB + 生成 API + Publer）→ Phase 21.B（week-view UI）。与 Phase 23 记忆协同。',
    dependsOn: ['1-6', '12.B', '8.12'],
    blocks: [],
    keyFiles: ['src/app/api/clients/[id]/content-calendar/', 'src/app/dashboard/clients/[id]/content-factory/'],
    keyTables: ['content_calendar', 'social_plan'],
    tags: ['social'],
  },
  {
    id: '22',
    name: 'Data Intelligence Engine',
    status: 'planned',
    description: '旗舰能力：采集 + 分析 + 反馈学习引擎（Phase 23 抽取器的数据喂养层）',
    detail: '与 Phase 23 Cross-Agent Memory 协同：Data Engine 采集数据 → 喂养 Phase 23 自动抽取器。覆盖所有飞轮数据源统一接入。',
    dependsOn: ['12.C', '17.A'],
    blocks: ['22.D'],
    keyFiles: [],
    keyTables: ['flywheel_metrics', 'flywheel_outcomes'],
    tags: ['infra'],
  },
  {
    id: '22.D',
    name: '主动任务生成器 — AnomalyDetector + 诸葛亮 Proactive',
    status: 'planned',
    description: '两层架构：规则引擎检测异常 → AI 决策生成主动任务',
    detail: '层 1：AnomalyDetectorJob（无 AI，规则引擎）→ anomaly_signals 表。层 2：POST /api/ai/zhugeliang/proactive → flywheel_actions（source=proactive_signal）。5 个 MVP 检测规则：CTR 下跌>30% / ROAS<1.5 / 博客 0 篇 / 关键词跌出 Top10 / 社媒 30 天零内容。子任务：22.D.1 anomaly_signals 表 + 22.D.2 AnomalyDetectorJob + 22.D.3 proactive API + 22.D.4 前端触发入口。',
    dependsOn: ['12.G', '17.A'],
    blocks: [],
    keyFiles: [
      'src/lib/flywheel/anomaly-detector.ts',
      'src/app/api/clients/[id]/zhugeliang/proactive/route.ts',
    ],
    keyTables: ['anomaly_signals', 'flywheel_actions'],
    tags: ['infra'],
    subTasks: [
      { id: '22.D.1', title: 'anomaly_signals 表 + migration', done: false },
      { id: '22.D.2', title: 'AnomalyDetectorJob（规则引擎）', done: false },
      { id: '22.D.3', title: 'proactive API（诸葛亮 AI 决策）', done: false },
      { id: '22.D.4', title: '前端触发入口（cron / 手动）', done: false },
    ],
  },
  {
    id: '23',
    name: 'Cross-Agent Memory Layer',
    status: 'done',
    completedDate: '2026-05-28',
    description: 'PR #112 等待 merge。4 张 L3 记忆表 + MemoryService + 全 Agent 注入 + 自动抽取器 + FDE 仪表盘',
    detail: '23.A+D：4 张 L3 记忆表（patterns/failed/preferences/decisions）+ MemoryService + 诸葛亮注入 + 决策历史自动写入。23.B：FDE 标注 UI。23.D.2：张骞/华佗/鲁班注入 L3 记忆。23.C：自动抽取器（cron + 手动）。23.E：FDE 仪表盘客户记忆库页（四 tab + 行级编辑 + 抽取/导出）。',
    dependsOn: ['12.G', '12.A'],
    blocks: ['21', '22'],
    keyFiles: [
      'src/lib/memory/MemoryService.ts',
      'src/lib/memory/formatMemoryForPrompt.ts',
      'src/app/api/clients/[id]/memory/',
      'src/app/dashboard/clients/[id]/memory/',
    ],
    keyTables: ['client_patterns', 'client_failed_approaches', 'client_preferences', 'client_decisions'],
    tags: ['infra'],
    pr: '#112 (待 merge)',
    notes: '⚠️ PM 需运行 20260610000001_phase23_memory_tables.sql',
  },
  {
    id: '24',
    name: 'Execution Loop Closure',
    status: 'active',
    description: '执行闭环：zhuge_source 字段 + GEO Snippet 公开 URL + action-persister 修复',
    detail: '⚠️ PR #108 P1：migration ADD COLUMN IF NOT EXISTS 跳过已有列，旧约束拒绝 source=zhuge（待修复）。P2：action-persister 未比较 zhuge_session_id 就覆盖；publish-geo-snippet 返回 admin URL 而非公开 URL。',
    dependsOn: ['12.G', '12.A'],
    blocks: [],
    keyFiles: [
      'src/lib/execution/action-persister.ts',
      'src/app/api/clients/[id]/publish-geo-snippet/route.ts',
    ],
    keyTables: ['flywheel_actions', 'execution_items'],
    tags: ['infra'],
    pr: '#108',
    notes: '🔴 P1 迁移脚本 bug 待修复（PR #108）',
  },
]

export function searchPhases(query: string): Phase[] {
  if (!query.trim()) return PHASES
  // Strip "phase " prefix: "phase 18" becomes "18", "Phase 12.A" becomes "12.a"
  const stripped = query.toLowerCase().trim().replace(/^phase\s+/i, '')
  const q = stripped.replace(/\s+/g, '')
  if (!q) return PHASES
  return PHASES.filter(p => {
    const idNorm = p.id.toLowerCase().replace(/\s+/g, '')
    // Exact or prefix ID match: "12.a", "12", "7.3"
    if (idNorm === q || idNorm.startsWith(q)) return true
    // Match without dot: "12a" matches "12.A", "18a" matches "18.A"
    const idNoDot = idNorm.split('.').join('')
    const qNoDot = q.split('.').join('')
    if (idNoDot.startsWith(qNoDot)) return true
    // Keyword match in name, description, tags
    const text = (p.name + ' ' + p.description + ' ' + p.id + ' ' + p.tags.join(' ')).toLowerCase()
    return text.includes(q)
  })
}
